### ISSUE TITLE
CRUD within a DB transaction

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#100]
I'm wondering how to solve this problem with SuperGraph.

Now I have an endpoint like this:

```graphql
type Mutation {
  sellPlayer(player: PlayerInput!): Player!
}
```

The business logic here is:

1. check if the player's buyer has enough money
1. if not abort operation
1. if yes, ok, take that money from the buyer's account and deposit it to the owner's account
1. **do this in a DB transaction**

Now with SuperGraph is there a way to achieve this?

It's still CRUD, just a little different, don't you think?

**Comment by dosco** [comment]
You could do this at the Postgres DB level, create a sell_player table with a trigger to do this.

**Comment by frederikhors** [comment]
Good idea. Thanks for the tip.

Can you please re-open this until some of us find time to document this process in the docs?

So other people can also benefit and/or contribute.

**Comment by dosco** [comment]
I plan on working on docs for a bit this week. Will add a page full of common examples: db schema + config + graphql
