### ISSUE TITLE
Even with "DisableFunction: true" them still visible in introspection

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#110]
### What version of Super Graph are you using? `super-graph version`

`v0.14.35`

### Steps to reproduce the issue (config used to run Super Graph)

```go
{
  Name: "players",
  Query: &core.Query{
    DisableFunctions: true,
  },
},
```

### Expected behaviour and actual result

The functions are still visible in introspection info.

**Comment by dosco** [comment]
Yes this does not hide functions it only disables functions for a specific role + table combination. Introspection is not role specific. It should throw an error when you try to use it.

**Comment by frederikhors** [comment]
It would be cool if they also disappeared from the introspection because if I disable them it means that I don't need them and during development it is inconvenient to have all those functions that appear when I search for the name of the table.

But I understand that this is a NICE-TO-HAVE.

**Comment by dosco** [comment]
Fair enough would a general config option to disable all functions work for you?

**Comment by frederikhors** [comment]
> would a general config option to disable all functions work for you

Nope.

If I disable functions for table `players` maybe I need it for table `teams`.

_But I don't want you to spend precious time on this problem which is not urgent._

**Comment by dosco** [comment]
No worries just gathering the info. Never know who wants to jump on this :)
