### ISSUE TITLE
Use objects variables to handle operations like sorting and filtering

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#115]
It would be amazing to have operations like `sorting` and `filtering` as objects to use with variables.

Today I cannot use this:

```json
{
  "query": "query players($order_by: playerOrderBy!) {
    players(order_by: $order_by) {
      id
      created_at
    }
  }",
  "operationName": "players",
  "variables": {
    "order_by": {
      "id": "desc"
    }
  }
}
```

because of #114.

It would be amazing to also have filtering operations like:

```json
{
  "query": "query players($where: playerWhere!) {
    players(where: $where) {
      id
      created_at
    }
  }",
  "operationName": "players",
  "variables": {
    "where": {
      "and": {
        "price": {
          "gt": "10"
        },
        "not": {
          "id": {
            "eq": "5"
          }
        }
      }
    }
  }
}
```

In this way I can use variables in my javascript clients easily.

Am I wrong?

**Comment by dosco** [comment]
The entire `where` clause cannot be dynamic as it's actual generated SQL and this would mean a re-compile in production but I see what you're trying to achieve. I'll think on how to make more parts of the query dynamic. For now you can do this. I want to make writing this `where` clause easier so I think your suggestion is inline with that. Closing this for now.

```
 "query": "query players($where: playerWhere!) {
    players(where: {  and: { price: { gt: $price }, not: { id: { eq: $id } } }) {
      id
      created_at
    }
  }",
```

**Comment by frederikhors** [comment]
This is one of the biggest limitations to using SuperGraph for now for me for some applications.

Using a traditional approach (API backend with ORM or manual SQL) it is possible to manage the query as I want, I realize it, changing every column and every clause at the moment.

But this should also be possible with SuperGraph simply because sometimes it is absolutely necessary to have it (data-driven applications, table format).

Maybe we could have a "free scheme" - "special function" that doesn't pre-compile and instead "transform" at the moment: maybe it will be slower but certainly more dynamic and therefore more useful.

**Comment by dosco** [comment]
I'm very happy to announce that this feature now exists. To use it just add entries under the `order_by`  field for a table in the config. The keys (`price_and_id` or `just_id`) can then be used as the values for the variable used with the `order_by` argument in your GraphQL.

Config File:

```yaml
tables:
  - name: products
      columns:
        - name: category_ids
          related_to: categories.id
      order_by:
        price_and_id: [ "price desc", "id asc" ]
        just_id: [ "id asc" ]
```

GraphQL Query:

```graphql
query getProducts {
  products(order_by: $order) {
    id
    name
    price
  }
}
```

GraphQL Variables:

```json
{
  "order": "price_and_id"
}
```
