### ISSUE TITLE
If I use variables for "first" or "limit" it gives me error: "Value for argument 'first' must be a number"

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#116]
Using this payload:

```json
{
  "query": "query players($first: Int!) {
      players(first: $first) {
        id
        created_at
    }
  }
  ",
  "variables": {
    "first": 5
  },
  "operationName": "players"
}
```

it fails with:

```log
ERR  error="value for argument 'first' must be a number"
```

It's the same using `"5"` as a string in json.

It works instead using this payload with no variables:

```json
{
  "query": "query players($first: Int!) {
      players(first: 5) {
        id
        created_at
    }
  }
  ",
  "operationName": "players"
}
```

**Comment by dosco** [comment]
This might be a simple change however any reason you want to make this variable in my experience it is usually fixed. Also making it variable means we have to do an upper bounds check to ensure someone on the web does not cause a DOS by passing a very high value.

**Comment by frederikhors** [comment]
I think I understand what you're saying: "usually this is a fixed value".

Did I get it right?

I can also agree with you: for the most part it is like this.

But in some applications that value is either saved as a user setting (therefore variable) or it can change on the fly from the client interface (and therefore directly from the GUI that the user is using).

As you have noticed from the other issues, most of the values I need in the queries are variable.

**Comment by frederikhors** [comment]
However, we can set a maximum limit.

Example:

`choose_min(graphql_variable_value, 50)`

**Comment by dosco** [comment]
I'll take a look at making `after`, `before` and `limit` a variable.

**Comment by kyugao** [comment]
how's the progress by far? I meet this issue too.

**Comment by dosco** [comment]
You can now use variables for limit, first and last arguments the value passed to the variable has an upper bound defined by either the `limit` config param in table role configs or using the new `default_limit` config value. For example if the default_limit is set to 50 and you pass 100 to to the limit variable (eg. $limit), 50 will be the enforced limit.

**Comment by dosco** [comment]
Can I close this issue?

**Comment by frederikhors** [comment]
@dosco I think you can although I haven't tried it yet because due to this issue and issue https://github.com/dosco/super-graph/issues/120 I have not used `super-graph` anymore which I will be using again as soon as these are closed. ❤️
