### ISSUE TITLE
Move globals used in the `serv` package to their own struct.

### ISSUE THREAD

**Issue by dosco** [dosco/graphjin#12]
**What would you like to be added**:

The `serv` package maintains a set of global variables for things like database connection pools, loggers, compliers, config etc. I would like these to be wrapped in a struct and this struct be passed around to everywhere it's needed instead of using globals. 

```
var (
	logger   zerolog.Logger  // logger for everything but errors
	errlog   zerolog.Logger  // logger for errors includes line numbers
	conf     *config         // parsed config
	confPath string          // path to the config file
	db       *pgxpool.Pool   // database connection pool
	schema   *psql.DBSchema  // database tables, columns and relationships
	qcompile *qcode.Compiler // qcode compiler
	pcompile *psql.Compiler  // postgres sql compiler
)
```

**Why is this needed**:

Firstly this will make it easier to write tests. This can help with things like supporting multiple databases or instances, etc. Also its much cleaner than using globals.

**Comment by kardasis** [comment]
I'm looking at taking this on.  Am I right that the list has been reduced to the following:
```
var (
	log      *_log.Logger // logger
	zlog     *zap.Logger  // fast logger
	logLevel int          // log level
	conf     *Config      // parsed config
	confPath string       // path to the config file
	db       *sql.DB      // database connection pool
)
```

**Comment by dosco** [comment]
As far as I can recall yes.

**Comment by dosco** [comment]
Done
