### ISSUE TITLE
Allow AllowList without external file

### ISSUE THREAD

**Issue by gzuidhof** [dosco/graphjin#138]
**What would you like to be added**:
Instead of passing in the AllowList as a string signalling where the file lives, it would be great if it was possible to pass it in without an external file. Perhaps there could be an alternative option to pass in an `io.Reader` or even a string? This is only relevant for *library mode*.

**Why is this needed**:
I am running a small service which I distribute as a single binary with any external files baked in. I would like to prevent a separate config file for something that will never change.

**Comment by dosco** [comment]
I agree this should be a simple enough change.

**Comment by dosco** [comment]
Do you still need this? Re-open if you do.
