### ISSUE TITLE
Support custom different  databases

### ISSUE THREAD

**Issue by koolay** [dosco/graphjin#142]
**What would you like to be added**:
super-graph depend functions  of pg like `jsonb`.

**Why is this needed**:
We want to custom sql-build for `mysql` and `dremio`.

**Comment by dosco** [comment]
MySQL support is on my todo list. A recent major refactor simplified the `psql` package and extracted out the database introspection code into a separate package `sdata`  all of this work is towards making it easy to add in support for MySQL.

**Comment by koolay** [comment]
Greate work.

**Comment by koolay** [comment]
@dosco 
What's the roadmap?
Thanks

**Comment by hby07** [comment]
I had the same problem,I need to support multiple databases.Have you solved this problem?
I want to learn.
Thanks

**Comment by dosco** [comment]
Not yet but its top of mind. What databases do you want to support?

**Comment by koolay** [comment]
`mysql`  is my first.

**Comment by dosco** [comment]
MySQL support has been added.
