### ISSUE TITLE
db:setup should check if the db exists

### ISSUE THREAD

**Issue by warent** [dosco/graphjin#145]
**What would you like to be added**:

db:setup should check if the db exists. If it does, then it should offer in the CLI for the developer to run exactly like db:reset

e.g.

```
$ super-graph db:setup

The database [db] already exists. Do you want to drop it and reset? (Y/n)
```

**Why is this needed**:

User experience

**Comment by dosco** [comment]
This whole big was re-written so it should work. Re-open if not.
