### ISSUE TITLE
db:reset should run db:migrate down

### ISSUE THREAD

**Issue by warent** [dosco/graphjin#146]
**What would you like to be added**:

db:reset doesn't truly reset everything. It just drops the database and tries to re-run setup. I would expect reset to run db:migrate down, and then drop the database, then run setup.

**Comment by dosco** [comment]
It could but then it would be a lot slower for quick dev testing. Why do you want it to migrate down instead of just dropping?

**Comment by jacobblock** [comment]
Not OP, but for example custom types won't be deleted with table drops. One work-around is `IF EXISTS` in both the up and down migrations.
