### ISSUE TITLE
super-graph version does not show version number

### ISSUE THREAD

**Issue by warent** [dosco/graphjin#147]
### What version of Super Graph are you using? `super-graph version`

0.15.4

### Steps to reproduce the issue (config used to run Super Graph).

running `super-graph version` says "unknown version"

```
Super Graph (unknown version)
For documentation, visit https://supergraph.dev

To build with version information please use the Makefile
> git clone https://github.com/dosco/super-graph
> cd super-graph && make install

Licensed under the Apache Public License 2.0
Copyright 2020, Vikram Rangneka
```

I have to get the version number from my go.mod file

**Comment by dosco** [comment]
And you got this after doing a `make install`?

**Comment by warent** [comment]
I believe this is after doing `go get -u github.com/dosco/super-graph`

**Comment by dosco** [comment]
Yup this is the reason for including the build instructions in the output above. There is no way to insert build time values into Go binaries built with `go get` I wish there was. Use `make install` for the variables.


```
To build with version information please use the Makefile
> git clone https://github.com/dosco/super-graph
> cd super-graph && make install
```

**Comment by warent** [comment]
@dosco I just saw this doc and was reminded of this. Maybe will help provide inspiration for what you could add to your documentation: https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#with-go-toolchain

**Comment by dosco** [comment]
Thanks i'll take a look.
