### ISSUE TITLE
Support uuid UserID

### ISSUE THREAD

**Issue by warent** [dosco/graphjin#148]
**What would you like to be added**:

should be able to do something like:

`ctx := context.WithValue(context.Background(), core.UserIDKey, uuid.FromStringOrNil("809c986c-5dd2-4fe8-884a-3a19451f87ff"))`

If I just try:

`ctx := context.WithValue(context.Background(), core.UserIDKey, "809c986c-5dd2-4fe8-884a-3a19451f87ff")`

I get:

`ERROR: operator does not exist: uuid = integer (SQLSTATE 42883)`

**Why is this needed**:

**Comment by dosco** [comment]
This should work I'll take a look

**Comment by dosco** [comment]
I suspect the field you are using the `eq` operator on with the `$user_id` value is an integer field and not a uuid field. I tested this by creating a table `create table test (id uuid PRIMARY KEY);` and then after inserting a single uuid file into it querying it with the web ui (localhost:8080). If you're still seeing this could you share the SQL statement with me. If not publicly then over Discord DM.

```
query {
  test(id: $user_id) {
    id
  }
}

{
  "data": {
    "test": {
      "id": "809c986c-5dd2-4fe8-884a-3a19451f87ff"
    }
  }
}
```

**Comment by dosco** [comment]
Does this work for you? Re-open is not.
