### ISSUE TITLE
Support for POSIX regular expression

### ISSUE THREAD

**Issue by luigi-riefolo** [dosco/graphjin#157]
**What would you like to be added**:
Hi, first of all let me say thank you to all of you that created this project. Definitely one of the best ones I've seen in years.

I'll soon be starting using this project for work, but we have an additional requirement: support for POSIX regular expression as described here (9.7.3): https://www.postgresql.org/docs/9.3/functions-matching.html

**Why is this needed**:
It can extend the support for pattern matching.

I'll be more than happy to work on a PR if this request gets approved.

**Comment by dosco** [comment]
Would love to have that feature added in. We have support for `similar` and `not_similar` adding posix regex should very similar you can jus follow that code path.

**Comment by luigi-riefolo** [comment]
@dosco I'll take that as a yes then.
I'll start tomorrow.
