### ISSUE TITLE
Library mode: error in importing super-graph

### ISSUE THREAD

**Issue by dancarlocanlas** [dosco/graphjin#159]
Note: Not really sure what category this falls under

### Description:
Currently trying to use super-graph in library mode -- started with just following the code from the docs: https://supergraph.dev/docs/library

Though I get an error regarding the super-graph import:
```
go: found github.com/dosco/super-graph/core in github.com/dosco/super-graph v0.15.28
go: github.com/dosco/super-graph@v0.15.28 requires
	cloud.google.com/go@v0.60.0/go.mod: verifying module: cloud.google.com/go@v0.60.0/go.mod: cannot authenticate record data in server response
```

### Other details
- Go version: 1.14.4
- When I try to run `go get github.com/dosco/super-graph` within the go path directory, it seems to work fine

**Comment by dosco** [comment]
I was unable to recreate this issue. I've however asked on the Discord chat if anyone else has this issue I know several folks on there use it as a library. I also updated dependencies in the case that is somehow the issue.

**Comment by dosco** [comment]
Are you still seeing this. Trying with a newer version of Go?

**Comment by dancarlocanlas** [comment]
Hi, yes, currently no longer encountering this after updating Go version a while back. Will be closing this one. Thanks!
