### ISSUE TITLE
GraphJin supports mysql right now?

### ISSUE THREAD

**Issue by fineday009** [dosco/graphjin#162]
I saw the previous conversations in the issue list, it seens The Author is supporting MYSQL?
Anyone know where is the roadmap? Thanks a lot.

**Comment by dosco** [comment]
We don't currently support Mysql it's on the roadmap.

**Comment by dosco** [comment]
Queries and Subscription supported with MySQL 8+. Mutations not yet will work on it soon. As of now you can check the query examples in the godoc to see whats possible. Even complex features like cursor pagination, full-text search, JSON columns, simulated array columns, recursive relationships, polymorphic relationships all supported.
