### ISSUE TITLE
Error with the contains (@>) and contained_in (<@) operators in WHERE clause construction

### ISSUE THREAD

**Issue by ikepolinsky** [dosco/graphjin#163]
### What version of Super Graph are you using? `super-graph version`
Latest Master branch

### Have you tried reproducing the issue with the latest release?
Yes

### Steps to reproduce the issue (config used to run Super Graph).
Example Table/Query:

```
CREATE TABLE contacts (
	id serial PRIMARY KEY,
	name VARCHAR (100),
	phones TEXT []
);

query {
    contacts(where: {phones: {contained_in: ['XXX-XXX-XXXX', 'XXX-XXX-XXXY']}}) {
        id
        name
    }
}
```

### Expected behaviour and actual result.

Expected WHERE clause:

```
...
WHERE ((("contacts"."phones" <@ (ARRAY['XXX-XXX-XXXX', 'XXX-XXX-XXXY'])))
...
```

Actual WHERE clause generated, which causes the error `cannot determine type of empty array (SQLSTATE 42P18)`:

```
...
WHERE ((("contacts"."phones" <@ (ARRAY[])))
...
```

### Suspected Fix
I'm new to both Go and this project but I believe Lines 175 and 178 in core/internal/qcode/exp.go should be ```setListVal(ex, node)``` which is similar to the other ARRAY operations at lines 139 and 142. I was playing with the changes locally and making the suggested changes gave the expected output in this instance. 

https://github.com/dosco/super-graph/blob/d674f3770b15178bbb7f746924f3a7fcee5145cf/core/internal/qcode/exp.go#L175 https://github.com/dosco/super-graph/blob/d674f3770b15178bbb7f746924f3a7fcee5145cf/core/internal/qcode/exp.go#L178 https://github.com/dosco/super-graph/blob/d674f3770b15178bbb7f746924f3a7fcee5145cf/core/internal/qcode/exp.go#L139
https://github.com/dosco/super-graph/blob/d674f3770b15178bbb7f746924f3a7fcee5145cf/core/internal/qcode/exp.go#L142

**Comment by dosco** [comment]
Are you still seeing this?

**Comment by ikepolinsky** [comment]
Making the changes I suggested above worked for me locally. Unfortunately, I had to step away from my project that was using GraphJin to focus on other things and never got around to putting a PR together. In addition to this fix I wanted to create a few test cases.
