### ISSUE TITLE
go get github.com/dosco/graphjin/core

### ISSUE THREAD

**Issue by hby07** [dosco/graphjin#168]
go get github.com/dosco/graphjin/core@v0.15.48
go: found github.com/dosco/graphjin/core in github.com/dosco/graphjin v0.15.48
go get: github.com/dosco/graphjin@v0.15.48: parsing go.mod:
        module declares its path as: github.com/dosco/super-graph
                but was required as: github.com/dosco/graphjin

**Comment by dosco** [comment]
Sorry I had forgotten to tag the release `go get -v github.com/dosco/graphjin/core@v0.15.49`
