### ISSUE TITLE
JSON Schema download breaks on: cannot self reference in Expression query

### ISSUE THREAD

**Issue by JoWiel** [dosco/graphjin#169]
Hi, Thank you for this awesome library, love it!

When I'm trying to download the schema as a JSON file, the schema breaks.
I tried it via the webgui and via the apollo cli.  An example of this is;

`Cannot reference Input Object \"categoryExpression\" within itself through a series of non-null fields: \"and\"."
`
Downloading the SDL however, works. 

### What version of GraphJin are you using?
Latest, however I cannot validate.
Running command;

`$  graphjin version
`
Gives;

```
GraphJin (unknown version)
For documentation, visit https://graphjin.com

To build with version information please use the Makefile
> git clone https://github.com/dosco/graphjin
> cd graphjin && make install

Licensed under the Apache Public License 2.0
Copyright 2020, Vikram Rangnekar
```

### Have you tried reproducing the issue with the latest release?
Yes, I have I stumbled upon it, when trying to download the schema.
Second thing I did was trying it out via the default example.

### What is the hardware spec (RAM, OS)?
Linux via WSL2 (Ubuntu 20.04) 8gbs of ram

### Steps to reproduce the issue (config used to run GraphJin).
1. git clone https://github.com/dosco/graphjin
2. cd examples/webshop
3. docker-compose run api db:setup
4. docker-compose up

5 Go to localhost:8080
6. Click on schema
7. Click on Download
8. Click on JSON

### Expected behaviour;
A schema, I can download as a JSON file, via either the Web Gui or the Apollo CLI.

### Actual result;
`{"__validationErrors":[{"message":"Cannot reference Input Object \"categoryExpression\" within itself through a series of non-null fields: \"and\"."},{"message":"Cannot reference Input Object \"categoryExpression\" within itself through a series of non-null fields: \"not\"."},{"message":"Cannot reference Input Object \"categoryExpression\" within itself through a series of non-null fields: \"or\"."},{"message":"Type subjectOutput must define one or more fields."},{"message":"Cannot reference Input Object ...`

**Comment by R-gues** [comment]
I currently have the same bug, GraphJin doesn't follow the spec about circular references: https://github.com/dosco/graphjin/issues/169
