### ISSUE TITLE
libtest/cmd.go: potentially unnecessary step in documentation

### ISSUE THREAD

**Issue by orlangure** [dosco/graphjin#170]
Hi there!

I'm the maintainer of [Gnomock](https://github.com/orlangure/gnomock), and I'm reaching out because I noticed you started using it in `libtest/cmd.go` just yesterday. Thanks for trying it out!

I also noticed a comment above `main` function in `libtest/cmd.go` stating that the following command needs to be executed before running it:

```
docker run --rm -p 23042:23042 -v /var/run/docker.sock:/var/run/docker.sock -v /Users/vikram/src/graphjin/libtest:/Users/vikram/src/graphjin/libtest orlangure/gnomock
```

I'm wondering what would be the reason to do so?

From what I'm seeing, you don't have to run `orlangure/gnomock` container. You could just use `gnomock.Start()` with whatever mysql/postgres preset you configured. `orlangure/gnomock` container is only required when your code is not written in Go: in such cases you could use Gnomock over HTTP from other languages, like python.

Can you try running the command without any prior setup?

**Comment by dosco** [comment]
Firstly, I want to just say thank you for Gnomock. I love the project and I'm working on moving all my tests to use it. I re-read your project README, I must have misunderstood. The section was titled `Using Gnomock server` and I just assumed it needed me to run a separate server I somehow didn't expect a Go library to internal launch and manage databases (I love that it does). Thanks for reaching out I'll fix this and drop you a note once I have all my tests running against multi databases using your library.

Do you have thoughts on adding Yugabyte and Cockroach both of which are Postgres compatible databases with fast growing adoption?

**Comment by orlangure** [comment]
> Do you have thoughts on adding Yugabyte and Cockroach both of which are Postgres compatible databases with fast growing adoption?

I opened new issues for CockroachDB (https://github.com/orlangure/gnomock/issues/92) and Yugabyte (https://github.com/orlangure/gnomock/issues/93), but I don't have any experience with any of them. It would be great if you could help to define preset requirements. Let's continue the discussion there 😼

**Comment by dosco** [comment]
Committed my first set of examples / integration tests using gnomock. It was what I wanted to do over a year go thanks for this project its very useful. Also it worked perfectly when the tests ran within a Github action. https://github.com/dosco/graphjin/commit/345fe8d65e58d4b51141afac5571e9e78c5cd957

**Comment by orlangure** [comment]
Great to hear, and thank you!
I have a draft for cockroachdb ready, so if you still need these two presets, please go ahead and let me know in the linked issues.
