### ISSUE TITLE
graphql alias not work well 

### ISSUE THREAD

**Issue by dengzhaofun** [dosco/graphjin#175]
SQL is normal in UI mode, with double quotes

SELECT jsonb_build_object('tasks', "__sj_0"."json") AS "__root" FROM (VALUES(true)) AS "__root_x" LEFT OUTER JOIN LATERAL (SELECT coalesce(jsonb_agg("__sj_0"."json"), '[]') as "json" FROM (SELECT to_jsonb("__sr_0".*) AS "json" FROM (SELECT "tasks_0"."id" AS "id", "tasks_0"."title" AS "title", "tasks_0"."reward_desc" AS "rewardDesc", "tasks_0"."draw_type" AS "drawType" FROM (SELECT "tasks"."id", "tasks"."title", "tasks"."reward_desc", "tasks"."draw_type" FROM "tasks" LIMIT ('20') :: integer) AS "tasks_0") AS "__sr_0") AS "__sj_0") AS "__sj_0" ON true

But Library schema SQL for some reason is missing double quotes,Causes the alias not to properly handle display

SELECT jsonb_build_object('tasks', __sj_0.json) AS __root FROM ((SELECT true)) AS __root_x LEFT OUTER JOIN LATERAL (SELECT COALESCE(jsonb_agg(__sj_0.json), '[]') AS json FROM (SELECT to_jsonb(__sr_0.*) AS json FROM (SELECT tasks_0.id AS id, tasks_0.title AS title, tasks_0.reward_desc AS rewardDesc, tasks_0.draw_type AS drawType FROM (SELECT tasks.id, tasks.title, tasks.reward_desc, tasks.draw_type FROM tasks LIMIT 100) AS tasks_0) AS __sr_0) AS __sj_0) AS __sj_0 ON true

example:

{
  tasks {
    id
    title
  	rewardDesc: reward_desc
    drawType: draw_type
  }
}

I spent an afternoon finding the reason but I don’t know how to fix it

**Comment by dengzhaofun** [comment]
I'm updating the command line to the latest version and I'm running into the same problem that seems to be caused by version iteration. How can I fix it. Camel case nomenclature for program uniformity

**Comment by dengzhaofun** [comment]
I rolled back the version to v0.15.56 alias and it worked fine

**Comment by dosco** [comment]
We had to remove `"`'s as part of the effort to support MySQL which does not use them. I'll have a fix out this week to revert back to using them.

**Comment by dengzhaofun** [comment]
After fixing the problem, close the issue, I can upgrade the version to the latest

**Comment by dosco** [comment]
Fixed in the latest commit. https://github.com/dosco/graphjin/commit/72db62ba968f9ea86bc3fd3c3c340c7a494a3d6e
