### ISSUE TITLE
Demo App example: password field doesn't exist

### ISSUE THREAD

**Issue by dbaroncelli** [dosco/graphjin#176]
Finally the Demo App runs:
https://graphjin.com/docs/intro

thanks @dosco 

I just wanted to point out a little problem in the sample query:
the password field doesn't exist

<img width="1303" alt="Schermata 2021-01-20 alle 12 34 19" src="https://user-images.githubusercontent.com/5320104/105169468-dd4d3000-5b1b-11eb-8ebe-3a417ff7fcd2.png">

**Comment by dosco** [comment]
The password field is part of the default block list if you need to fetch it then remove it from the block list in the `dev.yml` config file.

```
# Field and table names that you wish to block
blocklist:
  - ar_internal_metadata
  - schema_migrations
  - secret
  - password
  - encrypted
  - token
 ```

**Comment by dbaroncelli** [comment]
I just followed the instructions.
Run that query, and I got that error.

**Comment by dosco** [comment]
I've updated the docs. Will update the site soon.
