### ISSUE TITLE
documentation for the SIMPLEST use case

### ISSUE THREAD

**Issue by dbaroncelli** [dosco/graphjin#177]
It would be interesting the have the documentation for THE SIMPLEST use case:
retrieving data from a single database table
What is the minimum setup for running such basic GraphQL service?

Then, adding the 2nd SIMPLEST use case:
retrieving data from 2 database tables, connected by a field
what's the minimum setup for that?

if these 2 simplest uses cases are simple enough to setup,
then you would see a lot of adoption,
with people starting to setup more complex structures

Currently I am finding the documentation a bit overwhelming,
for people like me who have no experience with GraphQL.
Also it would be useful to get a documentation,
for connecting to an existing database, without using Docker.

I would be expecting to have a sample code, where you specify your database connection details and table name,
which can be compiled straightaway and run.

**Comment by dosco** [comment]
I agree will add a simple getting started guide. The short version of this is

Install GraphJin on your machine
```
git clone https://github.com/dosco/graphjin.git
cd graphjin
make install
```

Create a new GraphJin app, point it to your database and start GraphJin
```
cd ~
graphjin new my_app
cd my_app
<edit the config/dev.yml file to add your database user, password and host>
graphjin serv
```

Access the web UI in a browser
```
open http://localhost:8080
```

Now try some queries the UI has auto-complete to help you.

**Comment by dbaroncelli** [comment]
in the dev.yml,
I set these data:
```
database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  dbname: mytest
  user: root
  password:
```

but "mysql" is not recognized:
`ERR failed to connect to database: unable to open db connection: sql: unknown driver "mysql" (forgotten import?)`

**Comment by dosco** [comment]
Fixed in the latest commit.

**Comment by dbaroncelli** [comment]
Now I got a different error:
`SHELL my_app> ../graphjin serv`
```
restarting "./../graphjin" when it changes (additional dirs: ./config)
ERR failed to initialize: invalid foreign key table 'statement_analysis'
```

**Comment by dosco** [comment]
Thats unusual seems like you have a schema (database) that references the `sys. statement_analysis` table. We by default skip the following internal databases `information_schema, performance_schema, mysql and sys`. Feel free to join the Discord chat it might make it easier to debug the issue. FYI We don't as yet support references between multiple databases in short we only support a single database at a time for now it's top of list to fix going ahead.

**Comment by drewbitt** [comment]
This should be revisited for documentation. An example without the usage of `docker-compose` which the documentation has solely become reliant on would be welcome. I have no intention of using docker-compose.
