### ISSUE TITLE
Combing SQL with GraphJin

### ISSUE THREAD

**Issue by virtumonde** [dosco/graphjin#193]
Does GraphJin support ```hybrid queries```? By this I mean running SQL queries with GraphJin ones. My use case is that I want to run something like
```SELECT id, ST_Distance(t.x, thegeog) AS distance 
FROM   cafes c
    , (SELECT ST_GeographyFromText('SRID=4326;POINT(-76.000000 39.000000)')) AS t(x)
WHERE  ST_DWithin(t.x, thegeog, 2000)
ORDER  BY distance;
```
to retrieve the cafes located in a certain geographic area and then somehow capture them in GraphJin so that I would benefit from features like pagination.

**Comment by dosco** [comment]
I'm not familiar with geo queries however you can add variables to the config 

```yaml
variables:
    your_followers: "sql:select user_id from user_connections where connection_id = $user_id"
```

And then use them in GraphQL queries.

````graphql
query {
  users(where: { id: { in: $your_followers } }) {
    id
    name
  }
}
```

Another way could be to use database views.

**Comment by virtumonde** [comment]
This sounds great! Thank you, @dosco.
