### ISSUE TITLE
Nested where clause targeting related tables not working

### ISSUE THREAD

**Issue by nicocesar** [dosco/graphjin#196]
### What version of GraphJin are you using? `graphjin version`

v0.16.14 (inside docker container)

### Have you tried reproducing the issue with the latest release?

yes. Commit 8dbe15150db3ad4a6f981c4adc64a2afb833b8ad  with a postgres 11.11 database (needed to drop tsv column from the schema because it's not supported in that version, but it's irrelevant to this bug)

### What is the hardware spec (RAM, OS)?

16 Gb RAM, Linux 5.10.19-1, running docker compose  1.28.4, docker-engine (srv & client ) 20.10.2

### Steps to reproduce the issue (config used to run GraphJin).

(clone this repo in commit 8dbe15150db3ad4a6f981c4adc64a2afb833b8ad)
cd graphjin/examples/webshop
docker-compose up

### Expected behaviour and actual result.

The documentation says that "Nested where clause targeting related tables" are possible, so this should work:

```
query {
  purchases(where: {customer: {full_name: "Lukas Cronin"}}) {
    id
    customer{
      id
      full_name
    }
  }
}
```

But I get: 
```
{
  "error": "column: 'purchases.customer' not found"
}
```

On the other hand, this works: (no filtering):

```
query {
  purchases {
    id
    customer{
      id
      full_name
    }
  }
}
```

and this too: (filtering with no relationships)

```
query MyQuery {
  purchases(where: {customer_id: {eq: 1}}) {
    id
    customer {
      id
      full_name
    }
  }
}
```

**Comment by dosco** [comment]
I'll take a look later today.

**Comment by dosco** [comment]
Can you check if this works for you. Close the issue if it does.

**Comment by nicocesar** [comment]
Testeded. It works!. thanks, you can close the ticket
