### ISSUE TITLE
Sorting over aggregated column is not supported

### ISSUE THREAD

**Issue by ketankr9** [dosco/graphjin#201]
**What would you like to be added**:
Sorting over aggregation is not supported.
```
{
  billing_data (order_by: {sum_billingamount: desc}) {
    clusterid
    clustertype
    clustername
    sum_billingamount
  }
}
```
```
Error: "error": "column: 'billing_data.sum_billingamount' not found"
```
**Why is this needed**:
I want to sort the results based  on the aggregated data, this feature is very basic.

**Comment by dosco** [comment]
I agree this is useful and a must have will look into implementing it.

**Comment by ketankr9** [comment]
Hey @dosco I have implemented this feature https://github.com/ketankr9/graphjin/tree/utsav/aggregation_sorting_feature for my use case.    
I can raise a pr here if you can review.

**Comment by dosco** [comment]
I'll take a look today.

**Comment by dosco** [comment]
This looks good, looking forward to the PR.

**Comment by dosco** [comment]
I don't recall did you send me a PR for this?
