### ISSUE TITLE
Query variables not working?

### ISSUE THREAD

**Issue by nicocesar** [dosco/graphjin#203]
### What version of GraphJin are you using? `graphjin version`
```
GraphJin v0.16.16 
For documentation, visit https://graphjin.com

Commit SHA-1          : 919d3cc
Commit timestamp      : 2021-03-19 13:57:14 -0400
Go version            : go1.16.2

```
### Have you tried reproducing the issue with the latest release?
yes. `v0.16.16` is currently the latest

### What is the hardware spec (RAM, OS)?
16Gb RAM GNU/Linux

### Steps to reproduce the issue (config used to run GraphJin).
Create a query with a variable then use it with a variable:

![2021-03-26_17-14_1](https://user-images.githubusercontent.com/425081/112693406-f5f8ff80-8e56-11eb-9f6f-87af4e607496.png)
![2021-03-26_17-14](https://user-images.githubusercontent.com/425081/112693408-f6919600-8e56-11eb-8fbe-a9a46697a127.png)

### Expected behaviour and actual result.
Both queries should create the same output.

As a side note IDs are gen_random_uuid(): 

```
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE public.cards (
    id uuid DEFAULT public.gen_random_uuid() PRIMARY KEY,
(...)
```

**Comment by dosco** [comment]
In development mode you can use the X-User-ID: 4 header to set a user id so you don't have to worries about cookies etc. Headers  can be set using the `Request Headers` tab at the bottom of the web UI right next to the `Query Variables` tab.

In production `user_id` is extracted from the JWT token.

**Comment by dosco** [comment]
Did this fix your issue?

**Comment by nicocesar** [comment]
My appologies for the delayed reply. Just for the sake of completeness I'll reply. I upgraded to v0.16.35 and tried tio add X-User-ID to the headers, here is a screenshot (trying out insomnia now)

![imagen](https://user-images.githubusercontent.com/425081/114943884-b3eb2a00-9e14-11eb-88d4-f77588c2f7f5.png)

It still returning
```
{
  "data": {
    "cards": null
  }
}
```

**Comment by dosco** [comment]
I tested this as following and it works for me. Are you sure you have a row with a column `user_id` that matches the uuid you are using? 

```sql
CREATE TABLE users2 (
    id uuid PRIMARY KEY,
    full_name character varying NOT NULL,
    phone character varying,
    avatar character varying,
    email character varying NOT NULL DEFAULT ''::character varying,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```

![Uploading Screen Shot 2021-04-16 at 12.47.09 AM.png…]()
