### ISSUE TITLE
New app not created in Ubuntu

### ISSUE THREAD

**Issue by pyanishjain** [dosco/graphjin#209]
I install graphjin in my linode VPS using ubuntu 20. but when I run 
`graphjin new blog`

then error comes:
FATAL unable to create blog

**Comment by dosco** [comment]
Do you have the latest version. I'll release a new version tonight with more error reporting so you can see what the exact error is. Of the top of my head I think it's an issue with filesystem permissions maybe you are trying to create this blog on a path your user does not have write permissions to.

```
$ graphjin version

GraphJin v0.16.34
For documentation, visit https://graphjin.com

Commit SHA-1          : 844c520
Commit timestamp      : 2021-04-12 01:20:08 -0700
Go version            : go1.16
```
