### ISSUE TITLE
db:setup error

### ISSUE THREAD

**Issue by ldseraph** [dosco/graphjin#211]
db:setup will migrate schema to postgres dbname

https://github.com/dosco/graphjin/blob/ecb876b1e9184f012f76b5b79e7f05e4b80ca83b/internal/cmd/cmd_db.go#L23
before migrate not change set  useDB to true
https://github.com/dosco/graphjin/blob/ecb876b1e9184f012f76b5b79e7f05e4b80ca83b/serv/db.go#L95

**Comment by dosco** [comment]
Fixed sorry this was introduced by a major recent change to extract the entire `serv` package into a library so folks can use it within their own code. Let me know if it works for you.

**Comment by ldseraph** [comment]
nice. It's worked. But i find new bug. I will open new issue.
