### ISSUE TITLE
 cmd version show err

### ISSUE THREAD

**Issue by ldseraph** [dosco/graphjin#212]
### What version of GraphJin are you using? `graphjin version`
cmd version bug.  show unknown version

### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
x64

### Expected behaviour and actual result.

ldflags is not work

https://github.com/dosco/graphjin/blob/8390a5604fdd7dbe2ce1f92aee3390e0aef1ec1e/Makefile#L15

https://github.com/dosco/graphjin/blob/8390a5604fdd7dbe2ce1f92aee3390e0aef1ec1e/internal/cmd/cmd.go#L151

BUILD_FLAGS ?= -ldflags '-s -w -X "github.com/dosco/graphjin/serv.version=${BUILD_VERSION}" -X "github.com/dosco/graphjin/serv.commit=${BUILD}" -X "github.com/dosco/graphjin/serv.date=${BUILD_DATE}"'

**Comment by dosco** [comment]
Thanks for including the fix here and in the other issues appreciate the help.
