### ISSUE TITLE
scontext->gcontext?

### ISSUE THREAD

**Issue by ohkinozomu** [dosco/graphjin#216]
I don't know about the mean of "scontext", but if it's "Super Graph context", it should be renamed to "gcontext" or something.
https://github.com/dosco/graphjin/blob/c4c7fab21956c9fc40d053939b6033a9a9890456/core/core.go#L50-L57

**Comment by dosco** [comment]
I don't recall why I named it that you're probably right. I agree gcontext would probably be a better name. Feel free to send me a PR.
