### ISSUE TITLE
RLS security support via session variables

### ISSUE THREAD

**Issue by howesteve** [dosco/graphjin#23]
Hello,

I'd like to suggest a feature: setting current role from the session. That would allow RLS policies to be run using the session's user name, while not needing to set any securrity  models the config file.

My implementation suggestion would be hooking into sql generating and prepending the session user name like this:

conn.Query(ctx, 'SET session authorization howe; SELECT * FROM...')

This would allow reusing connections from the pool (as they already are) without more worries.

While we're at it, why not supporting session variables as well? They could be used on RLS policies, functions, triggers, etc. That woud be just as easy to implement:
conn.Query(ctx, `SET supergraph.company_id=1234; SELECT * FROM...')

Of course the '1234' parameter above should be sent as a parameter in the prepared query; that was just an easier to read example. 
 
Let's not forget to reset all those variables before running new queries; the final command should look like something this:
conn.Query(ctx, `RESET ALL;SET supergraph.myvar1='xxx'; SET supergraph.myvar2='yyy'; SELECT * FROM...')

I think there should be internally a hook for before sending queries to the server, and the standalone server should have a default implementation getting vars from jwt etc., but when running the server on embedded mode, the caller should be able to customize it. On jwt, the "sub" token should probably be the role name, and the payload could set the session variables.

I didn't have a deep look into the source, but should be easy enough to implement. I could look into it if you're not willing to implement this, but think it's a good idea.

Any comments?

Thanks,
Howe

**Comment by dosco** [comment]
I love this suggestion and thanks for the implementation details. Super Graph does have this but it currently uses transactions to set a local variables. I'm not sure how well it works with RLS polices.

```
  # Set session variable "user.id" to the user id
  # Enable this if you need the user id in triggers, etc
  set_user_id: false
```

This is the current code for it
```
func setLocalUserID(c context.Context, tx pgx.Tx) error {
	var err error
	if v := c.Value(userIDKey); v != nil {
		_, err = tx.Exec(context.Background(), fmt.Sprintf(`SET LOCAL "user.id" = %s;`, v))
	}

	return err
}
```

**Comment by dosco** [comment]
I'm also not clear on how `session` works. I know local is limited to the transaction but with session does it leak to every connection on the pool? 

Also getting extra vars from JWT sounds like a good idea.

**Comment by howesteve** [comment]
I hadn't look into that setLocalUserID() function and set_user_id. Very nice.
Basically it's the same idea for session/transaction variables. However for the user id you could still just set the current role (i.e. the SET ROLE command) then use [current_user] inside any queries or functions:
```
howe=# select current_user;
 current_user 
--------------
 howe
(1 row)

howe=# create role howe2;
CREATE ROLE
howe=# set role howe2;
SET
howe=> select current_user;
 current_user 
--------------
 howe2
(1 row)
```
RLS policies are typically written using [current_user] as well, and they are more portable - if a user logs using another client such as psql, they'd be enforced as well. This concept of setting role and variables is needed only because of the pool's connections reusing. 

Sessions are isolated on their own connections, so there is no leaking. The scope of session variables is just a little broader then a  SET LOCAL; for instance, if multiple transactions are about to be commited, a session variable could be used just once.  Other then that, should be mostly the same.

**Comment by howesteve** [comment]
Talking about implementation specifics - although I'm ok with settings "user.id", probably would be a better to create a default namespace for supergraph specific variables such as those set in the jwt header, avoiding collisions. 
In the case of "user.id", it would probably vanish if "SET ROLE xxx" is used.

**Comment by dosco** [comment]
So in short `SET Local` is the way to go and not `SET SESSION`? The reason I choose to set `user.id` instead of `set role` was that it required `create role`. While I know that's what PG requires I don't know of anyone who uses PG's internal `create role` and `create user` for managing users. Everyone I know has a users table that they defined.

**Comment by howesteve** [comment]
I see the following reasons for using SET SESSION:
1) Will work on SELECT statements as well - SET LOCAL does not.
```
howe=# set local session.id ='xxx';
WARNING:  SET LOCAL can only be used in transaction blocks
```
2) It could be issued only once if the same connection is used; so if the golang struct that prepares the SQL statements memorizes the last user, there is no need for another SET LOCAL (...  ) on every statement.
3) In the case of multiple commands issued in the same connection at a time, (does that happen at all inside supergraph?), there is no need to setup authorization and variables again.

The SET SESSION AUTHORIZATION has the advantage to use the built in authorization methods; listing some advantages: 
1) It's all inside the DB so it's more portable then using a built in sql generation schema
2) It's more secure as all - everything was tested by the PostgreSQL team.
3) It's easier to code - it's just regular sql setup, almost nothing inside supergraph - no yaml setup, etc. just the "SET AUTHORIZATION"/ SET VARIABLE... code
4) You could check permissions using any SQL you like: select queries inside a policy, using internal functions, etc.
5) Works with GRANT/REVOKE, CREATE POLICY, etc. - there are really many databases already using this.
6) Permissions are inhrerited, so you can add roles, add those roles to groups, and set permissions to groups, and have all those recursive complications handled by the database.
7) It works with other clients as well: use psql and do a "select * from mytable" - you'd see the same you see from the graphql client. 

I get your point about using an internal table for setting security, but it's limited and since RLS was not supported until a while ago, I guess developers fixed their own ways. 

The beaulty of this method is that you could do this:
```
CREATE POLICY user_mod_policy ON users
    USING (user_name = current_user);
``` 
You could also point to an internal users table, there are no limits on it.

There is some reference about it in here:
https://www.postgresql.org/docs/10/ddl-rowsecurity.html

**Comment by howesteve** [comment]
Btw putting it shortly, DBAs tend to design using database roles, and coders tend to use a table with an id. But both situations are common and both are perfectly addressable with the approach above.

**Comment by dosco** [comment]
> 2\. In the case of multiple commands issued in the same connection at a time, (does that happen at all inside supergraph?), there is no need to setup authorization and variables again.

This currently does not happen all GraphQL queries however complex are compiled to a single SQL query.

**Comment by dosco** [comment]
> The SET SESSION AUTHORIZATION has the advantage to use the built in authorization methods; listing some advantages:

I don't need convincing already a big fan of Postgres features like RLS. If people really knew Postgres they could throw away more than half of all current app code. 😄

The solution here is probably is to add a config value to enable setting current_user for those that want it. Also sounds like `set session` can be added to the generated sql query `set session blah=blah; select *...` and save us an extra round trip like now where a transaction is first created and then `set local` is called and finally the sql query is executed.

I'll have to look into how this would work with prepared statements since in production mode all queries are prepared at startup.

**Comment by howesteve** [comment]
> I'll have to look into how this would work with prepared statements since in production mode all queries are prepared at startup.
Good point, hadn't think about it. I guess there will be a couple more issues. But I agree prepending and avoiding an extra trip sounds like the better way to implement it.

**Comment by jcloutz** [comment]
It would be great to be able to have additional information set as session values accessible during queries. Postgraphile does this, and you can define what values are added in the config.. role, user_id, tenant id, oauth scopes etc.. It's super handy when using RLS.

**Comment by dosco** [comment]
Currently we allow setting one session variable `user.id` but we're considering deprecating (not decided as yet) that feature. The main reason for this is we have our own role based access control implementation that we can control per query. This level of control allows us to do things like attribute based access control where a query is run and access control rules are applied based on the values returned by that query.

More than any of this our highly-scalable subscriptions implementation is not compatible with RLS as it uses a single query for tens of thousands of subscribers.

**Comment by howesteve** [comment]
I wonder if it is a good trade-off to disable utilization of a built-in feature like RLS because the implementation of another feature (subscriptions) would not work with them? 
All my projects already use RLS not only because they are very safe, flexible and built into the database. But because their security will be available to other clients that are not using supergraph as well (say, someone connecting via JDBC or something). 
Doesn't look good to me to repeat the same hasura mistake and by going through the overhead of reimplementing all security permissions that are (or could be) already in the database... I know they are already there but I wish I could just use the database built-in support and not having to config long permissions list in a separate config file.
Besides, allowing session variables are very easy to implement (actually it's already there)...

Shouldn't we be able to **choose** between using session variables (RLS and other features) or optimized subscriptions? Just document, "hey, session variables do not work with this implementation of subscriptions"?

**Comment by dosco** [comment]
Fair enough. I understand the value of using RLS as it adds an additional layer of protection. The reason to implement filters and role based access control in Super Graph was to support the more popular multi-tenant use cases out there. The issue with RLS is that it's tied too tightly to the user and role stuff in Postgres which is very limited and does not scale well outside of enterprise usecases.

I understand also that not everyone needs subscriptions so it's fine to disable that if session variables are required. Outside of  `user.id` do you expect any other session variables? Even if you want this to be open ended in a key value setting in the config I'd love to understand what those values would be?

**Comment by howesteve** [comment]
Not only a layer of protection, but portable - if I open the database with psql or any other client, permissions would be applied. Actually the database does look transparently as if it is a single tenant application without any additional WHERE clauses needs. RLS works with any expression the database can handle, not only roles. 
Actually I think it scales really well since it's all handled by the database server. But yes, it is specially well suited to multi tenant cases and inherited roles - see the `pg_has_role()` function, it's really handy and can handle situations that would be very hard to do on other ways.
For instance, this is an actual policy in a database of mine:
``` sql
create policy history_select_policy on history
  for select
  using (pg_has_role(current_user, role, 'member'));
grant insert on history to public;
```
Also with RLS you can define much less permissions since the rules will apply even on joins/references.

I think user.id is the main variable that is required, but the following could be useful:

`user.tenant_id` ==> tenant/company/etc.
`user.session_id` 
`user.data` - arbitrary data, like some json string. That should handle all other cases.

Here is an example of multi-tenant setup with RLS not using built in roles:

https://aws.amazon.com/pt/blogs/database/multi-tenant-data-isolation-with-postgresql-row-level-security/

See how they use `current_setting('app.current_tenant')` to send the tenant id to RLS, and how well that performs and is easy to setup. Again, it's all built in and no need to rewrite queries with WHERE clauses.

Actually I personally prefer using built in roles because I want inherited roles permission and for that, I use pg_has_role(). But RLS can handle all kind of implementations.

**Comment by warent** [comment]
Agree, please don't deprecate session variables, or if you do then only do so for the purpose of enhancing/expand on them. At the moment the only reason why I'm choosing supergraph is because of the set_user_id parameter. I'm hoping in the future that what @howesteve outlined above is possible as well.

**Comment by dosco** [comment]
No worries I won't be deprecating it. Open to expand support for more session variables with the warning that `subscriptions` won't work with it. I'd be happy to help if you want to work on any additions or changes in relation to this. Also if there are any low hanging things that will make life easier for you let me know.

**Comment by gregwebs** [comment]
This issue is closed, but it's hard to figure out how to do RLS with graphjin. Can anyone document this at least with a comment on this issue? How to set the user variable appropriately when using Graphjin?

**Comment by gregwebs** [comment]
It looks like the configuration `set_user_id: true` will still set a variable `users.id`. But what is the way to actually set the current_user? Or are policies expected to look at users.id?
