### ISSUE TITLE
Support for Camel Case

### ISSUE THREAD

**Issue by dosco** [dosco/graphjin#231]
Hello,

Is there any support or thoughts to having the ability to take in a query with camel case fields, translate to snake case for the db and then output in camel case?

Or are there any settings for this?

The reason I ask is that my preference is snake case in the db, but camel case in API interaction and wanted to get your thoughts.

_Originally posted by @twhit-mrwebapps in https://github.com/dosco/graphjin/discussions/228_

**Comment by dosco** [comment]
I'll take a look later today

**Comment by twhit-mrwebapps** [comment]
Very excited, thank you

**Comment by twhit-mrwebapps** [comment]
Hi Dosco,

I downloaded you're new version and I think I've discovered a possible bug.

I have 2 db tables, states & countries

`query {
    states {
        id,
        country {
            phoneCode,
            countryCode
        }
    }
}`

DB Tables:

`CREATE TABLE countries (
        id CHARACTER(26) NOT NULL,
        country_code VARCHAR(5) NOT NULL,
        country VARCHAR(100) NOT NULL,
        phone_code INT DEFAULT 0,
        has_postcode BOOLEAN DEFAULT false,
        sort_order INT DEFAULT 0,
        PRIMARY KEY (id)
)`

`CREATE TABLE states (
        id CHARACTER(26) NOT NULL,
        state VARCHAR(100) NOT NULL,
        country_id CHARACTER(26) DEFAULT NULL,
        timezone_id CHARACTER(26) DEFAULT NULL,
        PRIMARY KEY (id)
)`

I get the following error:
2021/05/23 18:10:04 column: 'countries.y_code' not found

I also get the same error when calling countries by itself

`query {
    countries {
        phoneCode,
        countryCode
    }
}`

I suspect it may be attempting to translate part of a field incorrectly.

**Comment by dosco** [comment]
Good catch I know whats causing that bug its the `count` part of `countryCode`

**Comment by dosco** [comment]
fixed!
