### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by gedw99** [dosco/graphjin#232]
**What would you like to be added**:

federation

**Why is this needed**:

i have existing golang servers that expose GRPC and graphql.

It would be cool if we could reuse those fronted by this graphjin

**Comment by dosco** [comment]
Several ways to handle this 

1. Use the built in scripting extend it to handle GRPC. https://github.com/dosco/graphjin/wiki/Guide-to-GraphQL#adding-business-login-with-javascript

2.  Add a custom resolver for GRPC and GraphQL we currently have a built-in one for REST APIs
https://pkg.go.dev/github.com/dosco/graphjin@v0.16.72/core#Resolver

**Comment by gedw99** [comment]
thanks you !!

Will look deeper..  closing...
