### ISSUE TITLE
Failed to execute seed file config/seed.js: ReferenceError: i is not defined

### ISSUE THREAD

**Issue by shnads** [dosco/graphjin#238]
### What version of GraphJin are you using? `graphjin version`
GraphJin (unknown version) built using 'go get' on the 15th June 2021.

### Have you tried reproducing the issue with the latest release?
I built using 'go get' yesterday, unsure if that's considered the latest release?

### What is the hardware spec (RAM, OS)?
Macbook Air, OSX Big Sur.

### Steps to reproduce the issue (config used to run GraphJin).
run 'graphjin new testproject'
run 'cd testproject'
run 'docker compose run api db:setup'

### Expected behaviour and actual result.
I would expect the DB to be setup and the seed.js to run. Instead I get the following:

Failed to execute seed file config/seed.js: ReferenceError: i is not defined at seed.js:5:6(6).

Easy to fix by changing the line 'for (i = 0; i < 10; i++) {' in seed.js to: 'for (let i = 0; i < 10; i++) {'.

**Comment by shnads** [comment]
Note this is extremely easy to fix manually but may present an obstacle for new users. I would hate for someone to be turned off this brilliant project!

**Comment by dosco** [comment]
Thanks fixed with PR https://github.com/dosco/graphjin/pull/242
