### ISSUE TITLE
Incorrect fields in introspection query result

### ISSUE THREAD

**Issue by shnads** [dosco/graphjin#239]
### What version of GraphJin are you using? `graphjin version`
GraphJin (unknown version) built using 'go get' on the 15th June 2021.

### Have you tried reproducing the issue with the latest release?
I built using 'go get' yesterday, unsure if that's considered the latest release?

### What is the hardware spec (RAM, OS)?
Macbook Air, OSX Big Sur.

### Steps to reproduce the issue (config used to run GraphJin).
run 'graphjin new testproject'
run 'cd testproject'
run 'docker compose run api db:setup'
run 'docker compose up'
Visit the GraphIQL interface at localhost:8080

### Expected behaviour and actual result.
I would expect the 'usersOutput' type to not have a 'users' field (that is also of type 'usersOutput').

See attached screenshot for the actual result.

![image](https://user-images.githubusercontent.com/5667894/121976200-ad524200-cdc6-11eb-9215-618868e98f47.png)

**Comment by annymosse** [comment]
also it fallback into the root type instead other relationship :
```gql
type User{
  id: ID!
  email: String!
  posts: [Post!]
}

type Post{
  id: ID!
  title: String!
  body: String!
  user: User!
}
```
```js
gql`
query UserPosts{
   user(input:{id:1}){
      id  email
     posts{id title body } #<--- it should show up this relationship
     users{id email} #<--- , but it fallback to the root itself
}
`
```

**Comment by dosco** [comment]
I'll take a look.

**Comment by dosco** [comment]
Should be fixed. re-open if not.
