### ISSUE TITLE
Cannot find /telemetry

### ISSUE THREAD

**Issue by dosco** [dosco/graphjin#253]
### Discussed in https://github.com/dosco/graphjin/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **alexandervantrijffel** July 25, 2021</sup>
According to the docs at https://github.com/dosco/graphjin/wiki/Tracing-and-Metrics, when telemetry is enabled, the zPages UI should be available at /telemetry. I am running a graphjin app in development mode and OpenCensus telemetry is enabled according to the log:

```
api_1     | INFO	OpenCensus telemetry enabled
api_1     | WARN	OpenCensus: no metrics exporter defined
api_1     | INFO	GraphJin started, version: v0.16.92, host-port: 0.0.0.0:8080, app-name: Graphjintest Development, env: development
```

Config:

```
telemetry:
  debug: true
  interval: 5s
  tracing:
    exporter: "zipkin"
    endpoint: "http://zipkin:9411/api/v2/spans"
    sample: 0.2
    include_query: false
    include_params: false
    exclude_health_check: false
```

Where can I find the zPages UI? I would expect it to be available at http://localhost:8080/telemetry but that request returns a 404.</div>

**Comment by dosco** [comment]
I'll take a look

**Comment by ohkinozomu** [comment]
`http://localhost:8080/telemetry/tracez` and `http://localhost:8080/telemetry/rpcz` should work

**Comment by ohkinozomu** [comment]
`http://localhost:8080/telemetry/rpcz` and `http://localhost:8080/telemetry/tracez` would work.

**Comment by dosco** [comment]
Updating docs.

# OpenCensus tracing and metrics: when debug is enabled you will get
# a debug web ui. More info at https://opencensus.io/zpages/go/ 
# Rpc Stats: http://<host>/telemetry/rpcz 
# Trace Spans: http://<host>/telemetry/tracez
