### ISSUE TITLE
Config Refresh via Github Repository

### ISSUE THREAD

**Issue by rkumar0322** [dosco/graphjin#258]
**What would you like to be added**:
As a developer, I would like my configurations to be able to be reloaded from github, so that any graphjin service can experience zero downtime or redeployment. Specifically, the allow list file (including being able to update the file in github), and any configuration file are the most important ones that would help me out the most.

**Comment by dosco** [comment]
This has been implemented. You can use the hot-deploy feature as a github action to achieve this.
