### ISSUE TITLE
Hot Reload of DDL

### ISSUE THREAD

**Issue by rkumar0322** [dosco/graphjin#264]
As a Developer, I would like any schema changes that get committed to git to automatically reload the DDL and retrigger an application using graphjin, so that any ddl changes do not require any redeployment.

**Comment by dosco** [comment]
This commit added a much requested feature hot-deploy you can now use a new command `graphjin deploy` to push new configs instantly no rebuild and docker deploy needed. https://github.com/dosco/graphjin/commit/bc19e96a4e8272f9aa15bea3bd7b299b704ba4b5
