### ISSUE TITLE
graphjin go install problem

### ISSUE THREAD

**Issue by sergiopp** [dosco/graphjin#268]
Hi
I'm trying to install Graphjin using Go and I'm getting this output: 

`go: downloading github.com/Azure/go-autorest/autorest/to v0.4.0
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.`
        
I don't know if this is a Graphjin or a Go installation problem. 

I used this command to install Graphjin:

`go get github.com/dosco/graphjin`

Thanks in advance, have a nice week!

**Comment by dosco** [comment]
maybe try upgrading go

**Comment by sergiopp** [comment]
Thanks I'll try

**Comment by dosco** [comment]
Re-open if this is still an issue for you.
