### ISSUE TITLE
Use Apollo Client with Graphjin as a library

### ISSUE THREAD

**Issue by tschwann** [dosco/graphjin#269]
Greetings!
I would like to use use the Apollo Client with GraphQL. Where would Graphjin fit into this? It seems to me one would need to use something like  [this](https://github.com/graph-gophers/graphql-go). Am I correct? What are the pros and cons of using Grapjin as a library or as supposed to the whole service?

**Comment by dosco** [comment]
https://github.com/dosco/graphjin/wiki/GraphQL-with-ReactJS
