### ISSUE TITLE
Same subscription not updated

### ISSUE THREAD

**Issue by slava-vishnyakov** [dosco/graphjin#284]
Related to #283

I open two JavaScript clients, both of them request a subscription to:

```graphql
subscription newUsers {
  users() {
    name
  }
}
```

When opening a first client, in about 5 seconds, I get a list.

When opening a second client, I don't get anything back.

This stalls until I change the table, then both clients get an update.

Expected bahavior:

When connecting a second client, I should immediately get results back (instead of getting nothing), then wait for updates.

**Comment by slava-vishnyakov** [comment]
It seems that this only happens if the first connection is still alive.

I'm guessing GraphJin starts the query, figures out there are no changes (on second update) and doesn't send anything to the second client, despite the fact, that the client got nothing previously.

If that's the case, I'm suspecting there might be another bug where two different clients got two different datasets (say one of them connected way later than the first), but they will get the same update on poll.

**Comment by dosco** [comment]
I was meaning to make this fix it would require caching the results of the subscription. It's a little complex will work on it. Also yes I would love to have the first result return instantly instead of the 5 second wait. I need to refactor that code a bit.

**Comment by slava-vishnyakov** [comment]
Thank you!

**Comment by dosco** [comment]
Fixed
