### ISSUE TITLE
unexpected "subscriptions"

### ISSUE THREAD

**Issue by slava-vishnyakov** [dosco/graphjin#285]
I create a subscription to a query to a table named `subscriptions` (which contains `user_id`):

```graphql
subscription newSubscriptions {
    subscriptions(where: {user_id: {eq: "ca3ea1fd-ad87-4ba4-8228-198fbf4dbab8"}}) {
        user_id
    }
}
```

I get this in the console:

```console
WRN allow list save: graphql: syntax error: unexpected "subscriptions", 
expecting "fragment" (line 1, column 14)
graphql: syntax error: unexpected "subscriptions", expecting "fragment" (line 1, column 14)
```

Same thing happens with a query:

```graphql
query newSubscriptions {
    subscriptions(where: {user_id: {eq: "ca3ea1fd-ad87-4ba4-8228-198fbf4dbab8"}}) {
        user_id
    }
}
```

I don't get the same error when doing this:

```graphql
query newSubscriptions {
    users(where: {id: {eq: 1}}) {
        id
    }
}
```

So, it seems like this is related to the `subscriptions` table name.

**Comment by dosco** [comment]
Its. a reserved word I suggest renaming your table.

**Comment by slava-vishnyakov** [comment]
This will be very hard for newcomers, since they don't know it's a reserved word. Maybe you should add a clear error message then?

**Comment by dosco** [comment]
Ya that makes sense, will think of a solution or go with the error message

**Comment by dosco** [comment]
Have a fix in place it should just work now.

**Comment by slava-vishnyakov** [comment]
Excellent, thank you!
