### ISSUE TITLE
Variables in subscriptions don't seem to work

### ISSUE THREAD

**Issue by slava-vishnyakov** [dosco/graphjin#286]
I tried using `graphql-ws` with subscriptions - it generally works, however I can't figure out how to pass variables there.

As far as I see for example [here](https://unpkg.com/graphql-ws@4.2.0/README.md), it should be passed in `variables`, which generates the following WebSocket request:

```
{"id":"56851fd0-....","type":"subscribe","payload":{"query":"\n      subscription newSubscriptions {\n        subscriptions(where: {user_id: $userId}) {\n          channel {\n            name\n          }\n          unread_count\n        }\n      }","variables":{"userId":"280b74ac-1c79-11ec-97f9-0242c0a85002"}}}
```

1. GraphJin does not reply to this (it should probably explicitly complain to the client)
2. I see the following in the console of GraphJin: `Subscription Error: ERROR: column _gj_sub.userId does not exist (SQLSTATE 42703)`

**Comment by slava-vishnyakov** [comment]
If I replace $userId with explicit string (embedded), it seems to work. But it's unsafe, for sure.

**Comment by dosco** [comment]
I use https://altair.sirmuel.design/ to test subscriptions variables seem to work there.

**Comment by slava-vishnyakov** [comment]
Ok, sure, I'll try it an re-open if the issue persists.

**Comment by slava-vishnyakov** [comment]
Thank you!
