### ISSUE TITLE
I can't connect my local postgres database

### ISSUE THREAD

**Issue by brianwang** [dosco/graphjin#290]
### What version of GraphJin are you using? `graphjin version`
I am using  go install version on my Windows 10 pc

go get github.com/dosco/graphjin

so currently , there is not a version .

![image](https://user-images.githubusercontent.com/242249/137112796-be38c36f-970e-4541-b859-f8e3104b5f9f.png)

### Have you tried reproducing the issue with the latest release?
Not yet. I have no idea how to compile it on windows.

### What is the hardware spec (RAM, OS)?
64G Ram and Windows 10

### Steps to reproduce the issue (config used to run GraphJin).
1. In my config folder, I create dev.yml and prod.yml with my local Postgres Version14 database, and with PG Admin4,it can connect it.
2. I using command `graphjin db migrate new alter_user_addtoken` and get the error output.
 `database ping: failed to connect to `
![image](https://user-images.githubusercontent.com/242249/137113369-5048a79b-7b53-43d7-a9b9-54fd701c3fe4.png)

3. I also new create a folder for test and it does not help
4. I think I should try another database?

**Comment by gevera** [comment]
Try upgrading graphjin to the newest version and use `--db-url ` option

See for more details here
