### ISSUE TITLE
Wrongly detect schema change when using TimeScaleDB instead of Postgres

### ISSUE THREAD

**Issue by diegosz** [dosco/graphjin#294]
There is no priority in this issue, think is enough to know that this happens.

### What version of GraphJin are you using?

v0.17.6

### Steps to reproduce the issue (config used to run GraphJin).

Instead of Postgres, use TimeScaleDB (for example with the docker image timescale/timescaledb-postgis:1.7.4-pg11)

### Expected behaviour and actual result.

It keeps detecting schema change, but in reality there was no schema change.

It's probable that the dbinfo hash computed in core/internal/sdata/tables.go is peeking some internal TimeScaleDB tables so it wrongly thinks that there was an schema change.

**Comment by pbrazdil** [comment]
FYI The same is happening with postgres which uses postgis. Another issue is that the introspection schema has 10 times more fields than in reality. I am planning on fixing it somehow soon, might submit PR.

**Comment by dosco** [comment]
> FYI The same is happening with postgres which uses postgis. Another issue is that the introspection schema has 10 times more fields than in reality. I am planning on fixing it somehow soon, might submit PR.

Happy to help merge any PR that you might have for this, looks like  valuable fix.

**Comment by dosco** [comment]
feel free to reopen if this issue still exists.

**Comment by gedw99** [comment]
@dosco is timescale db suppported ?

thos is the only reference to it I could find in the project.

**Comment by dosco** [comment]
Its not in my official integrstion testing list but from this thread it seems its supported. @diegosz do you know what internal timescale db tables i can exclude from the discovery query to fix this?

**Comment by dosco** [comment]
@pbrazdil your issue with the introspection should we fixed we re-wrote the whole subsystem.
