### ISSUE TITLE
Why is github.com/btcsuite/btcd in the go.mod file

### ISSUE THREAD

**Issue by milerL** [dosco/graphjin#295]

**Comment by Krocsky** [comment]
effected by BTCD cpuminer, i try to use some old version......
it also download series of cryptocurrency miner files.

**Comment by Krocsky** [comment]
github.com/dosco/graphjin v0.17.3

it's fine

**Comment by dosco** [comment]
Its in there cause of the magiclink library. It's not in the default built only enabled through a build flag. However I plan to remove the magiclink library since this issue has been raised before a few times.
