### ISSUE TITLE
Embed PostgreSQL 

### ISSUE THREAD

**Issue by gedw99** [dosco/graphjin#299]
Before submitting a PR I want to check if your cool with this concept.

**What would you like to be added**:

https://github.com/fergusstrange/embedded-postgres

**Why is this needed**:

will make docker and non docker use the same mechanism. The docker would be only a standard golang docker that installs the db if not there. Idempotent too.

Will make it easier to boot strap an environment if your not using docker.

Make packaging for docker and non docker the same . 

There is also the possibility of using the same lib to pull the db at runtime, rather than embed it into graphjin. This pull make full upgrades and migrations concise because we can upgrade PostgreSQL itself also

**Comment by dosco** [comment]
We use gnomock to to embed postgres for all our intgeration tests

**Comment by gedw99** [comment]
Ah missed that .

will check it out .

 I need to deploy graphjin without docker to many bare metal systems.

**Comment by dosco** [comment]
Interesting use case. You could use the Graphjin `serv` package in your own app as well as `postgres-embedded` that way your one single app can start graphjin and postgres and it would all be packaged together without any docker in a single binary

**Comment by gedw99** [comment]
Thanks for tip !!

will give it a whirl :)
