### ISSUE TITLE
Validation Layer of data

### ISSUE THREAD

**Issue by magicMustard** [dosco/graphjin#305]
I'd like to get more information on what options we have for validating data in mutations.

I might be a bit out of my depth with this project, however I don't see many options in relation to adding validations apart from adding them at the DB layer.

I'm not particularly fond of that approach. I'd like to know what features are available to be able to get the dataset from the user, validate then process if available.

Alternatively, this is a feature request about adding middleware to validating the data.

One way I think is that you could do validation at the Column level? But food for thought.

Look forward to your responses.

**Comment by dosco** [comment]
Validation can be handled in the client end and as check and other constraints at the database column level. This way GraphJin does not have to deal with it and it's enforced.

**Comment by gedw99** [comment]
I made an issue that had some scope to do with Validation.

https://github.com/dosco/graphjin/issues/300

Its a bit convoluted, in terms of he way i described it, but the gist of it is if we use JSON Schema to describe the data schema we can use that same JSON Schema to do validations.

@dosco seems to think it was not too bad an idea, but i have not had much time to work on it.

if you want to explore it together that would be cool. Like making a game plan and prototype.

**Comment by dosco** [comment]
FYI - Support for validations is now added directly into GraphJin using the `@validate` or `@constraint` directive like so. I have to document this on the wiki but it's available.

```
mutation createUser
@constraint(variable: "email", format: "email", min: 1, max: 100) 
@constraint(variable: "full_name", requiredIf: { id: 1007 } ) {
  users(insert: { id: $id, email: $email, full_name: $full_name }) {
    id
    email
    full_name
  }
}
```

**Comment by magicMustard** [comment]
Oh wow, this is cool!

So, in the documentation you provide, I'm thinking you'll have what constraints rules you have available? Is there a way to define custom ones? For example, you have format: "email" - is it possible to be able to define maybe a regex rule just as an example?

Apart from that, this is great as well. I don't mind the idea of DB level regulation, I'm more thinking from a business use case level, you may have certain conditions to which not all regulations fit everyone - if you get my drift.

Well done!

**Comment by dosco** [comment]
We use a lot of the rules from this library https://github.com/go-playground/validator it's pretty extensive but yes regex should be easy to add.
