### ISSUE TITLE
Camel Case Support Extend To Mutation Variables

### ISSUE THREAD

**Issue by magicMustard** [dosco/graphjin#323]
**What would you like to be added**:

A few months ago, we discussed adding a feature for Camel Case and there is a setting to control this behavior.

I'd like to see this extended to mutated variables as well.

`{
    "insert": {
    "id": "01FVPABVWGDG4VBD76N9XCBWwg",
    "first_name": "Elliot",
    "last_name": "something",
    "email": "fragile_something",
    "policy_group_id": "01FVPABVWFS242TE0FCX5J7RHH",
    "phone": "something",
    "dob": "2022-01-01"
    }
}`

I'd prefer to be able to provide camel case variables and they'd be converted into the snake case vars.

**Why is this needed**:
Well, I can't recall the term for it. But if I'm querying the database and get a user for example, I should be able to copy the dataset returned and paste it as update variables and it should process.

Which means that the system should accept the variables for camel case when mutating the object.

**Comment by dosco** [comment]
I was meaning to do this a while ago thanks for the reminder. I just committed a fix for this let me know if it works for you. https://github.com/dosco/graphjin/commit/12244607f7ebee5ffed115e54ac0c2fb6aae76bf

**Comment by magicMustard** [comment]
Hey,

I tried it and it looks like something might still be missing. Here is the error I have:

> ERROR: null value in column \"policy_group_id\" of relation \"users\" violates not-null constraint (SQLSTATE 23502)

Here are the DB examples (using postgres)

`CREATE TABLE policy_groups (
        id CHARACTER(26) NOT NULL,
        group_name VARCHAR(100) NOT NULL,
        active BOOLEAN NOT NULL DEFAULT true,
	cache_id VARCHAR(100) NOT NULL default '000',
	created_at TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
	deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
	PRIMARY KEY (id)
)`

`CREATE TABLE users
(
	id CHARACTER(26) NOT NULL,
	policy_group_id CHARACTER(26) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(100) NOT NULL,
	dob DATE NOT NULL,
	active BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT null,
	deleted_at TIMESTAMP WITH TIME ZONE DEFAULT null,
	PRIMARY KEY (id),
	CONSTRAINT FK_USER_PR_GROUPS FOREIGN KEY (policy_group_id) REFERENCES policy_groups (id)
)`

Here is the mutation I have:

`mutation createUser {
  users(insert: $insert) {
    id
    email
    firstName
  }
}`

Variables:

`{
    "insert": {
    "id": "01FVPABVWGDG4VBD76N9XCBWw2",
    "firstName": "Elliot",
    "lastName": "something",
    "email": "nuggets@gmail.com",
    "policyGroupId": "01FVPABVWFS242TE0FCX5J7RHH",
    "phone": "something",
    "dob": "2022-01-01"
    }
}`

Are there any additional config settings?

**Comment by dosco** [comment]
There is the one `enable_camelcase` have you enabled this?

**Comment by magicMustard** [comment]
Yes, I do have it enabled. Just checking, the latest version I have is this one: 

github.com/dosco/graphjin v0.17.16-0.20220212082356-12244607f7eb

That should be the latest version with the changes?

**Comment by magicMustard** [comment]
Hey @dosco - Just following up when you get a chance, were you able to look into this? Is there anything you'd like me to test?

**Comment by dosco** [comment]
Sorry will look into this later today.

**Comment by magicMustard** [comment]
Hey @dosco - How did you go with this?

**Comment by dosco** [comment]
Sorry, this and couple other issues are on my plane. Just got busy will have a fix out in the next couple days.
