### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x200 pc=0xc56ae7]

### ISSUE THREAD

**Issue by raydcode** [dosco/graphjin#335]
### Expected behaviour and actual result.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x200 pc=0xc56ae7]

goroutine 500 [running]:
github.com/valyala/fasthttp.(*RequestCtx).Done(0xc002d9aca8)
	/home/qc/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/server.go:2691 +0x7
context.propagateCancel.func1()
	/usr/lib/go-1.17/src/context/context.go:280 +0x50
created by context.propagateCancel
	/usr/lib/go-1.17/src/context/context.go:278 +0x1d0
[127.0.0.1]:51950 08-Mar-2022 312:06:06  200  -  POST     /graphql
2022/03/08 12:32:07 server.go:39: exit status 2
exit status 1

**Comment by dosco** [comment]
This does not seem to be a GraphJin issue since we don't use `github.com/valyala/fasthttp` in our code. From the stacktrace it seems the the segfault is with fasthttp it's possible you are using Graphjin also in this app but it's not in the stacktrace. Feel free to reopen if you have more details.

**Comment by raydcode** [comment]
Thank you there is an outdated issue in our app now  resolved
