### ISSUE TITLE
Add support for only reading tables from specified schemas

### ISSUE THREAD

**Issue by mohsini172** [dosco/graphjin#336]
Currently if we try to `graphjin` as library, we need to call `core.NewGraphJin()` with a `config` value and `db` object. But there's no way to specify a **postgres** `schema` for which we want to generate the `Graphql`.
Is it possible?
If no, any ideas about how should we implement it? (I want contribute in it)

**Comment by mohsini172** [comment]
I actually looked into the `code` and even using a different schema for the `serv` package was not preventing it from generating **graphql** `queries`, `mutations` etc for other schemas. So I don't think it will be a small change and I don't think it's worth time and effort for now. 
For me personally, I'll be participating in a hackathon with different databases, rather than schemas so that will solve my problem for now.

**Comment by dosco** [comment]
Did you want to limit it to one schema? The discovery code pulls in everything since I want to allow folks to query across schemas.

**Comment by dosco** [comment]
We now have a `@schema(name: "blah")` selector level directive.
