### ISSUE TITLE
Allow Subscription Fan Out under 5 Seconds

### ISSUE THREAD

**Issue by jniclas** [dosco/graphjin#344]
Hey,

currently, if SubsPollDuration is less than 5 seconds, the Subscribe method uses 5 seconds as default.

**What would you like to be added**:
Keep 5 seconds as default, but also allow values under 5 seconds.

change the condition here: https://github.com/dosco/graphjin/blob/f32a17d1db67d7b5b9fc2ee02feca475f45d4762/core/subs.go#L195

**Why is this needed**:
I am writing a chat bot, that currently takes 5 seconds to answer cause it uses the Subscribe method. That feels very slow for the flow of conversation. 

best regards
Niclas

**Comment by dosco** [comment]
It was just a stop gap to prevent folks from polling the db too fast. I could change it to say 250ms or less do you have a suggestion? I'll make this fix today as part of some other updates but feel free to send a PR if you have an idea around a more sophisticated way to handle this. 

I was thinking of making it more dynamic by tracking overall query latency.

**Comment by jniclas** [comment]
Hey, I have tested different durations locally and below 200ms I could no longer see any increase in performance. So maybe 200ms is a good lower limit.
And maybe the SubsPollDuration should also be the upper bound for the random wait here? Next to the 500ms?https://github.com/dosco/graphjin/blob/f32a17d1db67d7b5b9fc2ee02feca475f45d4762/core/subs.go#L324
And I will think about how to make it more adaptive 👍🏻

**Comment by dosco** [comment]
Also don't I have to remove this conversion to seconds for this to work?

https://github.com/dosco/graphjin/blob/f32a17d1db67d7b5b9fc2ee02feca475f45d4762/core/subs.go#L198

**Comment by jniclas** [comment]
yes, looks like you're gonna have to.

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/graphjin/commit/0ed18b263754048d10ef065f6a1605ece498e714
