### ISSUE TITLE
rename core to compiler

### ISSUE THREAD

**Issue by switchupcb** [dosco/graphjin#347]
**What would you like to be added**:
Clarification on the usage of the GraphQL to SQL compiler ( `core`) via name scheme.

**Why is this needed**:
It's said that the `core` of GraphJin represents its GraphQL -> SQL compiler, but it isn't obvious from the name `core`. In actuality, it may be a better idea to create a standalone compiler package, but also unnecessary. Renaming core isn't actually practical.

**Comment by dosco** [comment]
I just went with the name `core` at the time. We could rename it in `/v1` as to not break anyone.
