### ISSUE TITLE
Blank Web UI

### ISSUE THREAD

**Issue by yudaprama** [dosco/graphjin#351]
### What version of GraphJin are you using? `graphjin version`
GraphJin v0.17.26

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
Linux

### Steps to reproduce the issue (config used to run GraphJin).

1. git clone https://github.com/dosco/graphjin
2. cd graphjin && make install
3. graphjin new try
4. Adjust database info on dev.yml
5. graphjin serve

![image](https://user-images.githubusercontent.com/33281225/165940125-44fa2434-2151-4c4e-808b-35657ef06b37.png)

**Comment by dosco** [comment]
I could not recreate this issue this is what I followed the below steps and the UI worked for me.

```
git clone https://github.com/dosco/graphjin
cd graphjin && make install
graphjin new try
cd try
docker-compose run api db setup
docker-compose up
open http://localhost:8080
```

**Comment by yudaprama** [comment]
Thanks, my fault!

Closing this

**Comment by gedw99** [comment]
on a mac i had to do it this way in order to make the web gui exposed.

```
git clone https://github.com/dosco/graphjin
cd graphjin && make install
graphjin new try
cd try
docker-compose run api db setup
docker-compose run -p 8080:8080 api serve
open http://localhost:8080
```

there is a issue around how i came to arrive at this solution here: https://github.com/dosco/graphjin/issues/358
