### ISSUE TITLE
Unable To Set Fields To An Empty Array

### ISSUE THREAD

**Issue by VandalSausage** [dosco/graphjin#362]
It looks to me that empty arrays are being refused in the parser and therefore aren't seen as valid values for array fields. This is happening in our prod environment using GraphJin as a service but I've put together a minimal replication using the quick start instructions.

### What version of GraphJin are you using? 

`v0.17.30` (is confirmed not present in v0.17.15)

### Have you tried reproducing the issue with the latest release? 

yes

### What is the hardware spec (RAM, OS)? 

16gb mac

### Steps to reproduce the issue (config used to run GraphJin).

Create a new graphjin instance `graphjin new test_1`

Add an array field to the boiler-plate local graphjin instance (0_init.sql)

```sql
CREATE TABLE users (
    id NOT NULL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,    
    email VARCHAR(255) NOT NULL,    
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    test_array VARCHAR(255)[] DEFAULT ARRAY[];;VARCHAR(255)[] NOT NULL,
    UNIQUE(email)
);
```

go through the quick start steps to get the graphjin server running

send a mutaion to the users table setting the test_array field to an empty array

query:
```graphQL

mutation {
       users( where: { id: { eq: $id } }, update: $data){
                id,
                test_array  } 
           }
```
 
variables:
```json
 { "id":3, "data": { "test_array" : [] } }
```

### Expected behaviour and actual result.

Expected reponse:

```json
{ "data": { "id": 3, "test_array":[] } }
```

Actual response

```json
{ "errors": [{"messgae": "List cannot be empty"}] }
```

**Comment by dosco** [comment]
I'll take a look.
