### ISSUE TITLE
Any Chance Of Adding Support For pgxpool?

### ISSUE THREAD

**Issue by magicMustard** [dosco/graphjin#366]
I was just thinking of trying to use the pgxpool for example. Potentially slightly more performance?

So just curious on being able to use the graphjin library with pgxpool?

**Comment by dosco** [comment]
If you're talking about using GraphJin as a library (`core` package) then we use anything that works with the standard `sql.DB` interface

**Comment by magicMustard** [comment]
Think I've found it, might close this unless I have further questions.

**Comment by ashokkumar88** [comment]
@magicMustard Did you find any workaround to use pgxPool?

**Comment by magicMustard** [comment]
I ended up modifying the project myself to support it
