### ISSUE TITLE
Roles Caching

### ISSUE THREAD

**Issue by magicMustard** [dosco/graphjin#368]
**What would you like to be added**:

Well, I notice that the interface to access roles information connects to the DB by the roles query.

I'm wondering what could be done to potentially reduce that requirement?

Not sure what you think might be appropriate, however, I was thinking, what if I had the ability to provide the Roles for the GraphQL call to use, I would tell it which ones to use from the conf file. In this sense, I could cache and control the access to the roles instead of having to call the db, and on the GraphQL call, I can provide the roles to use.

Alternatively, another solution might be perhaps instead of a RolesQuery, I have the option to provide a func that would then be used to provide which roles to use (based on the match and name).

In my example, I might do something along the lines of:

// Very crude function example
func (c *core.Config, userId) *Role {
    for _, r := range c.Roles {
        if r.Name == userId {
            return r
        }
    }
}

**Why is this needed**:
I'm building a very customised project in which access can be dynamically be controlled by both users and admins. i.e. a Sales Manager may wish to control their Sales team access.

Each time a request is made (from what I can see), we'd need to make an SQL call to the db to get the correct roles for that particular user.

Interested to hear your thoughts on the matter.

**Comment by dosco** [comment]
Total open to a PR for a callback function for selecting what role to use per query. Also roles can be extracted from the JWT token as well.

**Comment by dosco** [comment]
There are a couple ways to approach this one is to add a `Role` field to `ReqConfig` it will work for them folks are using the `core` package https://pkg.go.dev/github.com/dosco/graphjin/core#ReqConfig

And the other way is to add a hook function like the one we have for the result so folks using the `core` package can change the role etc based on the query and variables. https://pkg.go.dev/github.com/dosco/graphjin/serv#OptionSetHookFunc

**Comment by magicMustard** [comment]
I feel the ReqConfig would be more appropriate.... There is quite a bit of dependence on the "role" string, would what I'm proposing have much impact on that?

Having said all this, I must've done a man look as you mentioning the JWT proposal, I re-read the code and discovered that providing the UserRoleKey actually solves my concern nicely.
