### ISSUE TITLE
RBAC Filters Cause Intermittant Crashes

### ISSUE THREAD

**Issue by VandalSausage** [dosco/graphjin#369]
I have a possible reason for this failure after diffing through the src for a few days but I can't quite isolate it so I figured I'd create an issue. I'll add detail as I continue to investigate (might fork to add additional logging).

### Steps to reproduce the issue (config used to run GraphJin).

Essentially when I add a filter to a role, so using the example of the webshop, add a filter by user id on the product query, then I occasionally get an error that something like "column 'products.user_id' not found"

However this only happens when I have loads of filters (~15) and LOADS of tables across a lot of schemas in my db (around 300 total tables across 20 schemas).

Which leads me to think the filter validation might be being called before the database discovery is fully finished?

It's happening 95% in the lambda we've set up (using GraphJin as a service) but it occassionally happens in the local version I've got running.

I'm actively investigating so will add more detail as I find it.

**Comment by dosco** [comment]
Can you join the discord feel free to DM me if you don't want to share any queries publicly. 

> However this only happens when I have loads of filters (~15) and LOADS of tables across a lot of schemas in my db (around 300 total tables across 20 schemas).

Is this with a single query or just in general in the db and config?

> Which leads me to think the filter validation might be being called before the database discovery is fully finished?

Filter are compiled at startup time? Are you seeing this error on startup or when executing a query?

NOTE: Queries are compiled on demand and these above pre-compiled filters are inserted into the query at compile time.

**Comment by dosco** [comment]
Are you still able to recreate this? The `initSchema` and `initDiscover` functions are run well before the `addRoles` in called in `initCompilers` so this is probably something else and not that the db discovery and init has not completed. I'd love to help fix this.

**Comment by VandalSausage** [comment]
Yep, we've made no progress with this. It's intermittent but happens around 90% of the time.

It's only present when there is a filter on a table for a role in the config bundle.

The frequency of occurrence seems to be directly related to the number of columns in the db. 

If you have any suggestions for things we could investigate to help diagnose the issue that would be great :)

**Comment by dosco** [comment]
I'll create a 1000 column table and run some tests.

**Comment by VandalSausage** [comment]
Our set up is ~40 schemas, each with ~10 tables, each of those with 5 - 10 columns

**Comment by dosco** [comment]
I know its been a while but I had some time to look into this and created a test to generate 100 schema with like 10 tables each and try to recreate this issue. Since I don't personally use Schemas I've never dug into this feature as much. How do you write the graphql to ask for a table within a specific schema? We don't have support to specify the schema to use maybe we need this.

**Comment by dosco** [comment]
@VandalSausage I have added a test for your issue and some fixes including a new @schema directive to specify what db schema the selector referrs to. https://github.com/dosco/graphjin/blob/dfe77a966d8ebbdac739c28b2d5308a191038328/core/postgres_test.go

**Comment by dosco** [comment]
@VandalSausage If you are still experiencing this issue please reopen. I  have a fix and text in place not sure if it works for you.
