### ISSUE TITLE
It is just a question. How to make custom business logic in go?

### ISSUE THREAD

**Issue by gelleson** [dosco/graphjin#370]
I have read wiki but I didn't find some examples with custom logic in go.

**Comment by dosco** [comment]
If you're using GraphQL as a library you can implement custom logic before or after your call  to `graphjin.GraphQL`

**Comment by gelleson** [comment]
Got it. But can I extend GraphQL with new resolver built in Golang?

**Comment by dosco** [comment]
Here's an example of a custom Redis resolver. https://pkg.go.dev/github.com/dosco/graphjin/core#Resolver
