### ISSUE TITLE
Mutation not creating query yaml file

### ISSUE THREAD

**Issue by magicMustard** [dosco/graphjin#372]
### What version of GraphJin are you using? `graphjin version`
v0.20.4

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
Linux, Intel 6core, 16 gb.

### Steps to reproduce the issue (config used to run GraphJin).
`db, err := sql.Open("pgx", DsnStrBuilder())
	if err != nil {
		log.Fatal(err)
	}

	conf := &core.Config{
		DisableAllowList: false,
		Production:       false,
		Roles: []core.Role{
			{
				Name: "anon",
				Tables: []core.RoleTable{
					{
						Name:   "users",
						Schema: "rover",
						Query: &core.Query{
							Columns: []string{
								"id",
							},
						},
						Insert: &core.Insert{
							Columns: []string{
								"id",
								"first_name",
							},
						},
					},
				},
			},
		},
	}

	sg, err := core.NewGraphJin(conf, db)

	if err != nil {
		log.Fatal(err)
	}

	//query := `query findUsers{}`

	query := `mutation createUser {
		users(insert: $data) {}
	}`

	vars := json.RawMessage(`{
		"data": {
			"id": "01G6GZ1MN8EQ9PAQHR0KR809CV",
			"first_name": "Tim",
			"last_name": "somethign",
			"email": "woiefe",
			"phone": "04506gerge"
		}
	}`)

	ctx := context.Background()

	res, err := sg.GraphQL(ctx, query, vars, nil)

	if err != nil {
		log.Fatal(err)
	}

	var data interface{}

	if err = jsoniter.Unmarshal(res.Data, &data); err != nil {
		log.Println(err)
	}

	spew.Dump(data)`

I'm just doing some crude testing and I've created a mutation called "createUser" - however it does not seem to be creating a query.yaml file for said mutation.

When I change the confid to production to force use the allow list, it complains that the mutation does not exist.

Am I doing something wrong?

### Expected behaviour and actual result.
I suspect it should be creating a mutation query file?

Correct me if I'm wrong.

**Comment by magicMustard** [comment]
Noting it created the "findUsers" perfectly fine

**Comment by ehsanonline** [comment]
maybe this helps: https://github.com/dosco/graphjin/pull/361#issuecomment-1147842804

**Comment by magicMustard** [comment]
I did see that comment yesterday and tried testing it.

However, when I have it non-production mode meaning it should generate the query files, it is not creating the mutation query.

**Comment by ehsanonline** [comment]
test it with different mutations. remove all comments in your query. only if the mutation executes successfully it will create the query file.

**Comment by magicMustard** [comment]
Not sure what to say. Still getting the same thing:

`query := \`mutation createPolicy {
		policy_groups(insert: $data) {}
	}\`

	vars := json.RawMessage(\`{
		"data": {
			"id": "01G6GZ1MN8EQ9PAQHR0KR809CV",
			"group_type": "ACCOUNT",
			"group_name": "Test"
		}
	}\`)`

**Comment by ehsanonline** [comment]
change query to this:
```
mutation createPolicy { policy_groups(insert: $data) {   id   } }
```

**Comment by magicMustard** [comment]
Thank you ehsan, you were very helpful
