### ISSUE TITLE
Does not show the query builder in the left window

### ISSUE THREAD

**Issue by stilet** [dosco/graphjin#375]
### Steps to reproduce the issue (config used to run GraphJin).

`
graphjin new blog
cd blog
docker-compose run api db create
docker-compose run api db setup
docker-compose up -d

`

### Expected behaviour and actual result.

![graphginExplorer](https://user-images.githubusercontent.com/99677/178136862-a950a5ec-4c27-4aae-9103-9ed7189643ab.png)

**Comment by dosco** [comment]
I'll take a look
