### ISSUE TITLE
Unnamed queries cause subsequent queries to hang indefinitely.

### ISSUE THREAD

**Issue by akhudek** [dosco/graphjin#376]
### What version of GraphJin are you using? `graphjin version`

0.20.14 via homebrew

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

MacBook Pro M1 Max 32gb

### Steps to reproduce the issue (config used to run GraphJin).

Run any unnamed query. Eg. 

```
query {
  users {
    name
  }
}
```

### Expected behaviour and actual result.

Expected: The query returns results and the server continues to run.

Actual: The query returns results, but in the log we get `WRN allow list save: no name defined for query` and subsequent queries hang indefinitely.

Named queries work fine. E.g. 
```
query GetUsers {
  users {
    name
  }
}
```

**Comment by magicMustard** [comment]
I'll add a note that I'm getting the same issue.

Unnamed queries were working, but mutations would just sit there. Interestingly, it appears that the mutation actually inserted the value, however something afterwards must be happening and it does not return the result / error and I need to terminate the request.

I was using psql.

Let me know if you want the details.

**Comment by dosco** [comment]
I'll take a look. This would be a serious regression will prioritize it.
