### ISSUE TITLE
Err check missing in code

### ISSUE THREAD

**Issue by krish7919** [dosco/graphjin#393]
Error check missing at https://github.com/dosco/graphjin/blob/master/core/core.go#L140.

The code for reference is:

```go
        ...
        gj.schema, err = sdata.NewDBSchema(
		gj.dbinfo,
		getDBTableAliases(gj.conf))

	ssufx := gj.conf.SingularSuffix
	if ssufx == "" {
		ssufx = "ByID"
	}
	gj.schema.SingularSuffix = ssufx

	return err
```

But when `NewDBSchema()` fails and returns an error, the immediate next line at `gj.schema.SingularSuffix = ssufx` will fail with a `panic: runtime error: invalid memory address or nil pointer dereference` as `gj.schema` is `nil`.

### What version of GraphJin are you using? `graphjin version`
0.20.32

### Have you tried reproducing the issue with the latest release?
This is the latest release

### What is the hardware spec (RAM, OS)?
Go 1.19

### Expected behaviour and actual result.
The code should not fail, or return error earlier.

**Comment by dosco** [comment]
Fixed in https://github.com/dosco/graphjin/commit/01d54ca2edb1f0051fd7dd8e324239e773e75054
