### ISSUE TITLE
Hello, why usersByID is automatically generated

### ISSUE THREAD

**Issue by kxbin** [dosco/graphjin#399]
I customized the users table, why usersByID is automatically generated, is there any special usage of usersByID?

Thanks

**Comment by dosco** [comment]
I can't recall why it was added it was a while back. The only special thing about it is that it returns a single result as an object by default all other selectors return an array unless you use the `@object` directive.

**Comment by kxbin** [comment]
@dosco  Ok, I see. Thank you
