### ISSUE TITLE
Missing __typename at  top level causes errors with fluter_graphql

### ISSUE THREAD

**Issue by cchandel** [dosco/graphjin#404]
Hi,
   I was tying to use the https://github.com/zino-hofmann/graphql-flutter to query data from my local install of graphjin.
  
   Kept getting OpertionException errors till I figured out that graphql-flutter expects a top level __typename as well.

   Tried using postgraphile, and the errors went away.

   I would prefer using grpahjin, so do help.

Thanks.

**Comment by dosco** [comment]
does this work for you? please close this issue if it does.
