### ISSUE TITLE
dial error (dial tcp [::1]:5432: connect: cannot assign requested address

### ISSUE THREAD

**Issue by kaushalyap** [dosco/graphjin#406]
### What version of GraphJin are you using? `graphjin version`
v0.21.9 (Go binary install)

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
16GB, Fedora 37

### Steps to reproduce the issue (config used to run GraphJin).
Follow the detailed tutorial in docs up to following command

```
docker-compose run api db setup
```

### Expected behaviour and actual result.

```
❯ docker-compose run api db setup
Creating network "webshop_default" with the default driver
Creating webshop_db_1 ... done
Creating webshop_api_run ... done
WARN	database ping: failed to connect to `host=localhost user=postgres database=`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)
```

**Comment by dosco** [comment]
can't reproduct
