### ISSUE TITLE
Support Postgresql's `sslmode` parameter

### ISSUE THREAD

**Issue by plmercereau** [dosco/graphjin#420]
I could not find a way to pass on the `sslmode` parameter in the connection string, for instance, to set it to `require`. It is something that is possible to do?
Thanks in advance, very nice project

**Comment by gedw99** [comment]
This is what’s blocking me too

**Comment by dosco** [comment]
New `connection_string` config option under `database` use as you wish.
```
connection_string: postgres://jack:secret@pg.example.com:5432/mydb?sslmode=verify-ca&pool_max_conns=10
```

**Comment by gedw99** [comment]
Thanks @dosco 

If I recall correctly this should fix the cockroachdb connection issue too

**Comment by dosco** [comment]
let me know.

**Comment by plmercereau** [comment]
It works, thanks v much!
