### ISSUE TITLE
webui: Error fetching schema

### ISSUE THREAD

**Issue by tamal-appsbee** [dosco/graphjin#433]
Hi 
Using graphjin with go, following https://github.com/dosco/graphjin/blob/master/website/posts/go.md this tutorial "Using the service
". When browsing to this page : http://localhost:8080/webui/?endpoint=/graphql receiving following error:
![image](https://user-images.githubusercontent.com/8500385/233075691-05abadbb-5f43-484b-840b-95ece7c0164f.png)

**Comment by dosco** [comment]
Are you still having this issue. I tried to recreate it using the standalone service but could not.

```
cd graphjin
make install
cd examples/webshop
graphjin serve
open https://localhost:8080
```

**Comment by AbdulDridi** [comment]
I get this in staging (when deployed to a remote server) - but not in local: https://www.core.staging.findgg.com/webui/?endpoint=/graphql
