### ISSUE TITLE
I have a problem required variable 'user_id' of type 'integer' must be set

### ISSUE THREAD

**Issue by duolabmeng6** [dosco/graphjin#439]
<img width="1013" alt="image" src="https://github.com/dosco/graphjin/assets/59047063/c78b5279-4e43-427c-86a7-c1fe3f96f27d">

I checked the relevant documentation and found no instructions on how to set up the integer.

**Comment by duolabmeng6** [comment]
<img width="1005" alt="image" src="https://github.com/dosco/graphjin/assets/59047063/43ad9190-ad3f-4a1d-84a7-7c920cf8e5df">

**Comment by duolabmeng6** [comment]
Very distressed and unable to use

**Comment by duolabmeng6** [comment]
<img width="1155" alt="image" src="https://github.com/dosco/graphjin/assets/59047063/541119f0-dbf9-43e8-b8a0-87151d813c21">
I tried various ways

**Comment by dosco** [comment]
`user_id` cannot be set by from the client its automatically set by the authentication middleware for example after getting it from a valid jwt token. if you want to use a variable here try something like `my_user_id`
