### ISSUE TITLE
wasm / deno updates

### ISSUE THREAD

**Issue by gedw99** [dosco/graphjin#447]
hey @dosco 

Been playing with the wasm....

Can you add a script to show how to boot the wasm / deno compbo

BTW it works with gotip. no need for tinygo. gotip has the "new wasm" build in.

```sh
GOOS=js GOARCH=wasm gotip build -o graphjin.wasm .
GOOS=wasip1 GOARCH=wasm gotip build -o graphjin.wasip1 .
```

**Comment by dosco** [comment]
./wasm/make-tiny.sh has been added the build needs testing. the build is about 5mb smaller

**Comment by gedw99** [comment]
thanks @dosco  will try this out.

**Comment by dosco** [comment]
any thoughts on the the tinygo wasm build? also any thoughts on how gotip helps us?

**Comment by gedw99** [comment]
I don’t think we need gotip. The WASM updates are now in the released version of golang .

tinygo works well on most simple projects. 

Graphjin should work because it has simple dependencies. Reflection is still a bit of a work in progress. 

I will try to work on testing it but am pretty stretched right now. Would appreciate if you and others can update this issue with results …

**Comment by dosco** [comment]
It already compiles with gotiny and with the standard go compiler. But even with go tiny its not as small as I like it to be.

**Comment by gedw99** [comment]
Its server side though so who cares ?

**Comment by dosco** [comment]
That's true, some folks asked me the wasm build could be smaller it's used by the npm package for GraphJins Nodejs API. Thanks for the tip on wazero I did not know about it.

**Comment by gedw99** [comment]
Glad to help … 

Would be with also looking at the SQLite WASM that uses wazero too to get a head start . I am using it and it’s working really well 

https://github.com/ncruces/go-sqlite3

the perf is actually excellent too .

I am running it server side and client side in a browser . The client side is inky capable on in memory storage - just so you know.

May use case required sandboxing , because I need to run servers at the edge in all OS’s with out docker .
