### ISSUE TITLE
Incorrect SDL types generated for insert/update

### ISSUE THREAD

**Issue by nathanstitt** [dosco/graphjin#459]
Thank you for creating and releasing graphjin, I think the product has a lot of potential as an alternative to Hasura which I've used in the past.

However I hit a few apparent bugs with the SDL that is generated. It seems to require an ID argument for inserts/updates, and does not accept arrays for has-many foreign key relationships.

For instance the below should be a valid insert, and one of the tests actually calls it, however it appears they are sending strings and not validating against SDL. https://github.com/dosco/graphjin/blob/master/tests/insert_test.go#L432-L463 

I noted it when attempting to generate type safe typescript bindings using https://the-guild.dev/graphql/codegen

[](url)
Give this DB schema:
```sql
CREATE TABLE users (
  id BIGINT NOT NULL PRIMARY KEY, 
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE products (
  id BIGINT NOT NULL PRIMARY KEY, 
  name VARCHAR(255) NOT NULL,
  user_id BIGINT references users(id) on delete cascade,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

```

This GQL insert mutation
```
mutation createUserAndProducts {
  users(
    insert: { 
      id: 10051
      email: "test@test.com"
      full_name: "Anon"
      products:[
        {
          id: 10052
          name:"Test 1"
        }, {
          id: 10053
          name:"Test 2"
        }
      ]
    }) {
    id
    email
    full_name
  }
}
```

However the SDL types do not allow this in two ways:
The ID is required in users() 
<img width="630" alt="image" src="https://github.com/dosco/graphjin/assets/79566/a2bac734-619f-4ea5-a6ff-1eb0a106ab52">

And products do not accept an array:
<img width="809" alt="image" src="https://github.com/dosco/graphjin/assets/79566/446f442e-4b7f-4f56-b3da-1bf38d94cd1f">

The original error from codegen that started the exploration:

<img width="889" alt="image" src="https://github.com/dosco/graphjin/assets/79566/9b96ad9e-e896-4c02-a705-c1bc846e393c">

### What version of GraphJin are you using? `graphjin version`

`v3.0.18` git sha `0c4461a769a355328f803c0851c2663ea9ea5d63`

### Have you tried reproducing the issue with the latest release?

I am running latest version

### What is the hardware spec (RAM, OS)?

osx ventura M1 32gb, isn't hardware related tho

### Steps to reproduce the issue (config used to run GraphJin).

Run the explorer and perform an insert mutation without an ID.  Screenshots attached

### Expected behaviour and actual result.

You should be able to insert records without specifying an ID, and has-many relationships should accept an array

**Comment by rkrishnasanka** [comment]
Yeah, it seems like graphjin generates the primary keys as `ID!` in the basic graphql data types. It kinda screws the ability to query all the objects in the table too. 

This library is 90% there but needs another 10% to fully functional. Looking at the code doesn't help either because of the lack of code documentation.

**Comment by dosco** [comment]
Happy to fix this however it seems to be limited to the introspection query and the errors in the web ui are based off that but the query itself works fine without id's there are several integration tests around this. https://pkg.go.dev/github.com/dosco/graphjin/tests/v3

**Comment by dosco** [comment]
Fair enough, my familiarity with it probably blinds me to these issues. aiming to fix it and have much more detailed comments using an llm + myself.

> Document of architecture of the code. Currently the way the code is structured is not intuitive. There's repeated code between core and serv, super flat hierarchy, etc.

True on the variable naming and hierarchy. I am following the styles popular in the Go world. I'm tried to do a better job breaking things into smaller functions who's name are a bit more descriptive. And have also done by best to split domains and sub-systems into their own packages or files. 

At a high level `core` is the core compiler and it has almost no dependencies. It has its own config and handles database discovery, GraphQL compiling and the introspection and SDL stuff.

While `serv` is the standalone service (can also be used as a library) it contains the HTTP handlers, Auth, OpenTracing and many other things. It has several dependencies on other GraphJin packages and external packages

There's a rich integration test suite in the `tests` package (requires docker) and can be run with `make test` (run at the top level). We use `make` to do other things like build, releases, linting, etc.

The `cmd` package contains the code for the cli to which is used to create new GraphJin apps, run the standalone service, manage secrets, hot-deploy, etc

We also have a wasm build in `wasm` package used for nodejs library.

Lots of other stuff is in internal packages eg `core/internal` for example:
psql - SQL generation code (internal representation called `qcode` to sql)
graph - our graphql lexer and parser 
qcode - our abstract syntax tree (internal representation)
sdata - db discovery, db relationship graph, db schema file

**Comment by dosco** [comment]
This looks great will run the tests and merge the PRs
