### ISSUE TITLE
Rows limit, how SuperGraph detects it?

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#47]
Out of curiosity: how can SuperGraph detect there are more rows for a query if the limit in SQL query is the same limit on the Graphql query?

**Comment by frederikhors** [comment]
I'm asking it because I'm intrigued. I'm coming from hours on building a cursor pagination algorithm for a project.

**Comment by dosco** [comment]
If you are asking about cursor pagination then it does not know the cursor keeps moving the fetch window ahead by the limit number when the response is empty then you've reached the end. The complexity around cursor pagination comes into play when multiple complicated order by clauses are used.

**Comment by frederikhors** [comment]
Even if my English is not good, I think I understand that SuperGraph's cursor pagination is not able today to "predict" if there are even just one or more lines for the query clauses.

Correct?

I'm asking because of Relay's [HasNextPage](https://facebook.github.io/relay/graphql/connections.htm#HasNextPage()).

And anyway it's not a problem for me.

I'm just considering if it's possible to use it with Relay today.

Maybe leaving this issue open we can keep track of it.

**Comment by dosco** [comment]
Correct. Also it does not attempt to since tables are not fixed they have new rows added to them all the time. If for example we did tell you that there are no new rows and suddenly in the next second 10 more rows were added then you would not paginate further and miss them.

**Comment by frederikhors** [comment]
This is the "classic" pagination problem.

https://blog.apollographql.com/understanding-pagination-rest-graphql-and-relay-b10f835549e7

With classic "skip/offset" pagination we have the problem of added/deleted rows during navigation (and the OFFSET slowness when there are many rows).

With cursor pagination "à la Relay" we have the problem of "added" rows at the end, like you say. So we have to check anyway if we have new rows after latest cursor even if `hasNextPage` is false. In other words, we must always have a "Load more..." feature ready.

But also with your solution the problem is still there. When you reach the end of tables the cursor is empty. But in the next second 10 more rows can be added and we need to check with the "Load more..." feature, right?

Correct me if I'm wrong.

---

https://github.com/dosco/super-graph/issues/44 is related.

**Comment by dosco** [comment]
From this doc it seems `hasNextPage` is useless as they recommend ignoring it. Yes, but I would not say it's a problem since tables are always changing. When the cursor returned is `null` just use the previous cursor and try again.

**Comment by frederikhors** [comment]
> From this doc it seems `hasNextPage` is useless as they recommend ignoring it.

Which doc?

I agree with you for the rest.

**Comment by dosco** [comment]
Sorry I meant from your post 

> With cursor pagination "à la Relay" we have the problem of "added" rows at the end, like you say. So we have to check anyway if we have new rows after latest cursor even if hasNextPage is false. In other words, we must always have a "Load more..." feature ready.

**Comment by frederikhors** [comment]
I think we should reopen this or https://github.com/dosco/super-graph/issues/44 because we need a `start` cursor.

Maybe I'm wrong but it seems we need it to paginate in the reverse way.

Let's say a table has ids from `0` to `100` and I'm visiting page `3` (20-29).
Today SuperGraph is returning me cursor for `ID: 29`, but I need also the cursor for `ID: 20` if client needs to revert the pagination.

So we always need:

- `start` cursor
- `end` cursor (the one SuperGraph today has)

Am I wrong?

**Comment by dosco** [comment]
Reverse pagination has been documented https://supergraph.dev/guide.html#pagination. You can change the pagination direction using `last` or 'first'

```
query {
  products(last: 10, before: $cursor) {
    slug
    name
  }
}
```

**Comment by frederikhors** [comment]
I know that.

But still there is a problem.

In my client I can save the list of cursors coming from back-end but still I need a way to tell SuperGraph that I need rows `before` the `ID: 20` cursor and NOT `before` `ID: 29` or `ID: 19`; in other words I can't use a "Previous page" button with it because from `before` `ID: 19` I will skip `ID: 20` in pagination.

I know this is maybe a client problem, but I see around many graphql back-end (not only Relay) with `start` and `end` cursor and since you are an excellent person to talk to then I am asking for your wise opinion.

Am I totally wrong?

**Comment by dosco** [comment]
Have you looked into `limit-offset` pagination that might be better option for you.

```
query {
  products(limit: 10, offset: 100) {
    id
    slug
    name
  }
}
```

**Comment by frederikhors** [comment]
@dosco, I'm coming here again.

I think SuperGraph today has issues with `last` and `first`

The same query I'm trying with it and with Postgraphile: different results with `last`.

**Comment by frederikhors** [comment]
It seems to me that `last` is the same as if I use `first`. Same results.

**Comment by dosco** [comment]
`first: 3` gives me this

```
query {
  comments(first: 3) {
    id
  }
}
```

```
{
  "data": {
    "comments": [
      {
        "id": 1
      },
      {
        "id": 2
      },
      {
        "id": 3
      }
    ],
    "comments_cursor": "8NXoueG2t0d41fLYBtY2HUYSmNcP+qN+7Ui8aec="
  }
}
```

`last: 3` gives me this

```
query {
  comments(last: 3) {
    id
  }
}
```

```
{
  "data": {
    "comments": [
      {
        "id": 3027
      },
      {
        "id": 3026
      },
      {
        "id": 3025
      }
    ],
    "comments_cursor": "+OJ0pAkYKYH1jFbzh3mztJjrarDBbb7QsYrlSs0Uq+w="
  }
}
```

**Comment by frederikhors** [comment]
Oh, wow! I see the problem now.

The query I'm using is:

```
query players {
  players(
#   first: 5,
    last: 5,
    order_by: { score: desc },
  ) {
    id
    score
  }
}
```

where `score` is an `int8 NOT NULL` in Postgres.

When I comment the line `order_by: { score: desc },` it works (like in your example).

If I leave that line there the players are the with both `first` and `last`.

These are the generated SQL queries:

With `first: 5`:

```sql
SELECT
	"players"."id",
	"players"."score"
FROM
	"players"
ORDER BY
	"players"."score" DESC,
	"players"."id" ASC
	LIMIT ( '5' ) :: INTEGER
```

With `last: 5`:

```sql
SELECT
	"players"."id",
	"players"."score"
FROM
	"players"
ORDER BY
	"players"."score" DESC,
	"players"."id" DESC
	LIMIT ( '5' ) :: INTEGER
```

What changes is `"players"."id" ASC` > `"players"."id" DESC` which shows the same players to me.

**Comment by dosco** [comment]
The code to handle multiple order by with cursors is complex let me take a look. I suspect setting an order on the Id might have caused this

**Comment by dosco** [comment]
I'll take a look.

**Comment by frederikhors** [comment]
> The code to handle multiple order by with cursors is complex let me take a look. I suspect setting an order on the Id might have caused this

I know. I'm currently writing it manually. 😢 😄

**Comment by dosco** [comment]
The jd aka primary key is added as a tie breaker.

**Comment by dosco** [comment]
Can you post the result of the query only the id and score fields. The id is a tie breaker it's possible your scores are zero or low so it seems like it's not changing.

**Comment by frederikhors** [comment]
Oh. I can't now. I'm from the phone.

I was using Postgraphile too to queries results.

Scores is an `Int` (NOT `uint`) and `NOT NULL`.
