### ISSUE TITLE
Can Support Mysql ?

### ISSUE THREAD

**Issue by godla** [dosco/graphjin#48]
Can Support Mysql ?

**Comment by dosco** [comment]
It does not currently support MYSQL but I plan to in the near future.  I recently released Super Graph as a library so that is a first step towards supporting other SQL dialects.

**Comment by godla** [comment]
nice

**Comment by joseluisq** [comment]
It would be great if MySQL get support.
However I wondering why this ticket got closed.

**Comment by dosco** [comment]
Reopening, The original author of the ticket closed it. Yes MySQL support would be great. I have not had a chance to look into Mysql's support for `LATERAL JOINS` and `JSON`. I'd appreciate it if anyone could post some links on here to help with my research. Also does it make sense to target MySQL or MariaDB are they technically not the same?

**Comment by joseluisq** [comment]
> I have not had a chance to look into Mysql's support for `LATERAL JOINS` and `JSON`. I'd appreciate it if anyone could post some links on here to help with my research.

Those links can probably help:

- https://dev.mysql.com/doc/refman/8.0/en/lateral-derived-tables.html
- https://mysqlserverteam.com/support-for-lateral-derived-tables-added-to-mysql-8-0-14/

> Also does it make sense to target MySQL or MariaDB are they technically not the same?

General speaking yes, but they deffer a bit. Specially MySQL on its latest version with new features. 
For instance, MySQL 8 has introduced a new `sha256_password` and `caching_sha2_password` [authentication plugins](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html). The last one is enabled by default. So whereas MariaDB [doesn't support ](https://mariadb.com/kb/en/authentication-plugin-sha-256/) them yet.

Among other similarities and incompatibilities https://www.eversql.com/mariadb-vs-mysql/

**Comment by dosco** [comment]
Support for Mysql added.
