### ISSUE TITLE
add resolvers parameters to Service

### ISSUE THREAD

**Issue by LucaWolf** [dosco/graphjin#500]
**What would you like to be added**:
Add the user defined NewGraphJin or OptionSetResolver when creating Service (serv/v3) parameters.

**Why is this needed**:
serv has got a nice "webui" tooling but cannot (or not clear / don't know how) use bespoke resolvers with NewGraphJinService

**Comment by dosco** [comment]
If you mean "resolvers" as those defined in other GraphQL frameworks its not possible in GraphJin since its a compiler that directly compiles GraphQL to efficient SQL and executes that SQL directly on the DB there is no room for resolvers etc.
