### ISSUE TITLE
support pseudo-columns return query fields to the auto-generated schema

### ISSUE THREAD

**Issue by LucaWolf** [dosco/graphjin#501]
**What would you like to be added**:
Would like to have fields in query not supported by any existing columns in the DB. These should be able to resolve via user defined resolvers.

**Why is this needed**:
this way, the query response to the user could include additional fields derived from existing columns, leaving the original value untouched. 
Dummy example: "token" field resolved by some crypt( backend_key, sha(public.user.id, public.user.name) ) functionality.
Also, is unclear from documentation how can user defined resolvers can take more existing columns values as parameters.

**Comment by dosco** [comment]
Since GraphJin compiles Graphql to SQL directly there is no room to run resolvers within this SQL query. I would suggest using generated columns instead or creating a view on top and querying that. https://www.postgresql.org/docs/current/ddl-generated-columns.html
