### ISSUE TITLE
How to: cursor pagination for UUID primary key

### ISSUE THREAD

**Issue by LucaWolf** [dosco/graphjin#502]
The example used in docs uses `first` and `last`. 

These do not work when the PK of queried table is UUID. The error returned is:
**pq: function max(uuid) does not exist**. Please provide an example of how to address this scenario or explain docs if (which PK) are not supported.

**Comment by dosco** [comment]
I'm not familiar with uuid for pk columns are they ordered or random? They need to be ordered since cursor depends on the ability to sort on the column. You can try adding a max(uuid) function as shown here. https://dba.stackexchange.com/questions/275251/why-is-there-no-maxuuid-minuuid-function
