### ISSUE TITLE
Thoughts on generic adapters for different SQL servers? 

### ISSUE THREAD

**Issue by silasb** [dosco/graphjin#51]
**What would you like to be added**:

I'd love to use this with sqlite3.  Right now I see that a lot of stuff is coded for PostgreSQL. By using a adapter design we could build different versions that support sqlite3, mysql, mssql, etc...

**Why is this needed**:

Would make it easier to port to different SQL backends.

**Comment by dosco** [comment]
For the most part we stick to features in the SQL standard and not too many Postgres specific things. I agree with the point you're making currently work is underway to support CockroachDB and maybe MySQL next so it will give us some reference to what parts we can keep common and what parts we need to be able to customize.
