### ISSUE TITLE
Plurals / singulars -> realy needed? BC break

### ISSUE THREAD

**Issue by podhy** [dosco/graphjin#63]
Hi,
first I would like to say this project seems to be very promising. I'm already in testing phase.

One thing which I found in this project which seems to me annoying is the definition of singular and plurar "table" names when I'm calling them from graphql query.

Because I'm not native english speaker and some old projects are using mixed english and national language table names it looks realy weird when I need suffix these "tables" with "s" letter.

Wouldn't be better to return array of results or only base object based on full primary keys usage?

I know that this will create BC break but I'm only opening discussion about this.

(sorry for my english)

**Comment by dosco** [comment]
Just to be sure I understand what you want You are saying that you want the table named `tables` to return a single value? What you're saying makes total sense but i've found that often i need to use a query to fetch a single object and yes that could be an array too. Also fetch by primary key should ways be an object not an array response. Let me think about this also could you provide me some query examples if possible.

In the meanwhile would using aliases work for you?

```
query {
  tables : table {
  ...
  }
}
```

**Comment by podhy** [comment]
>You are saying that you want the table named tables to return a single value

for example I have DB table called `uzivatele` which means in enaglish `users`...when I want list all user a have to query it as `uzivateles`....I know its only cosmetic thing but it look weird :-)

>What you're saying makes total sense but i've found that often i need to use a query to fetch a single object and yes that could be an array too. Also fetch by primary key should ways be an object not an array response.

yes but this project makes some abstraction around relational database and in relational database if you dont use **full** primary key definition you cannot be sure if there is more than one row returned...yes you are limiting it by 1 on this project...but thats not IMO clean way

what am I suggesting is: look at list of parameters and if parameters presented in graphql query are equal to primary key columns then it should return single object otherwise array

>In the meanwhile would using aliases work for you?

didnt know about then I will have a look

**Comment by podhy** [comment]
>if you dont use full primary key definition you cannot be sure if there is more than one row returned

or UNIQUE contraint / index (all informations are in catalog)

**Comment by dosco** [comment]
Did the alias work for you for now?

**Comment by podhy** [comment]
yes alias si working
