### ISSUE TITLE
Some ideas from hasura project

### ISSUE THREAD

**Issue by lulucas** [dosco/graphjin#72]
**What would you like to be added**:

* custom http handler
* custom graphql handler
* postgres trigger handler

**Why is this needed**:

This is what my project is used with hasura.

![image](https://user-images.githubusercontent.com/19854458/83959399-10092780-a8af-11ea-812c-d0e9a596bad8.png)

The goal is to quickly build a single file api service, with easy deploying.

1. Why custom http handler, because some third party api service will call it, such as payment notification callback. Currently I have to use nginx to dispatch graphql request and http request to hasura or my http handler.

1. Why custom graphql handler, because login, register, and generate payment url for user. It's bored to write golang http code and redefine it in hasura action.

1. Why postgres triggert handler, like when a new user signs up, triggered a users table insert event to send a email to user.

I think hasura saves a lot of time for crud situation, but many tools make it easy for crud. 

The real troblue one I think is custom business logic and access control. I think super-graph does great job in access control, still missing a way to implement custom business logic.

It's inconvenient to deploy and devolpment now with hasura because I have to make nginx, hasura, golang worked together.

If super-graph can make all this needs on one golang project, and build to single binary service. It's really helpful to quick development and easy delopying.

**Comment by dosco** [comment]
GraphJin service and the graphql compiler are exported as go libraries which you can use to build whatever you need. This should work great for you. The GoDocs have a ton of examples.

https://pkg.go.dev/github.com/dosco/graphjin/core
https://pkg.go.dev/github.com/dosco/graphjin/serv
