### ISSUE TITLE
docker-compose environment documentation needed.

### ISSUE THREAD

**Issue by asharabu** [dosco/graphjin#79]
Hi,

I can see that below Postgres environment for supergraph docker container but unable to see the environment for the database. 

> 
Postgres related environment Variables
SG_DATABASE_HOST
SG_DATABASE_PORT
SG_DATABASE_USER
SG_DATABASE_PASSWORD

> 

Can you please let me know the environment variable for the database?

**Comment by dosco** [comment]
The database itself does not need any environment variables in development as is. For information about configuring the Postgres docker image it's best to lookup the Postgres docker documentation. https://hub.docker.com/_/postgres
