### ISSUE TITLE
Automatic persisted queries

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#88]
What do you think about **Automatic persisted queries (APQ)**?

- GqlGen: https://gqlgen.com/reference/apq/

- Apollo: https://github.com/apollographql/apollo-link-persisted-queries

- URQL: https://github.com/FormidableLabs/urql/tree/master/exchanges/persisted-fetch

I think SuperGraph (as a server at least) needs to handle this.

And for SuperGraph as a library we can write a recipe. Or we can handle it internally too?

**Comment by frederikhors** [comment]
After reading https://kevinjalbert.com/graphql-persisted-queries-with-http-caching-part-2 I think in our case it is even easier to implement APQ because we already have the "`allow.list`" file which could already contain the hash of each individual query.

**Comment by dosco** [comment]
I didn't know they were called that :) but I had planned to expose a REST api endpoint for of the queries in the allow.list. That way even people who don't want to use GraphQL in their clients can still use GraphQL. I just wanted to wrap up the highest priority stuff first but if you'd like to have a go at this I'm happy to provide guidance.

**Comment by kpbird** [comment]
@dosco I can implement basic APQ on super-graph with `github.com/go-pkgz/expirable-cache`. I can keep hash of query in `expirable-cache` and lookup before `compileQuery` and if the query found in lookup then skip `compileQuery`

I think is this quick and simple to implement. This can be improvised in future with a better solution 1. store query in Redis 2.  client end only hash instead of the full query etc..

**Comment by dosco** [comment]
That sounds pretty neat and should be more than enough. Storing queries in Redis is probably overkill for now :)

**Comment by kpbird** [comment]
@dosco Should I follow Apollo's APQ document to implement? (https://github.com/apollographql/apollo-link-persisted-queries)?

I implement as per Apollo's APQ then I also need to change super-graph as a library. currently, super-graph as a library has `res, err := sg.GraphQL(ctx, query, variables)`  GraphQL function which accepts only cx, query and variable but If I follow Apollo's APR then I also need to add one more argument `extensions`

Let me know what do you think?

**Comment by dosco** [comment]
APQ is supported out of the box.
