### ISSUE TITLE
Subscriptions via Server-Sent Events

### ISSUE THREAD

**Issue by frederikhors** [dosco/graphjin#97]
It would be amazing to support Subscriptions also via Server-Sent Events.

Here an example in JS: https://github.com/CodeCommission/subscriptions-transport-sse

**Comment by dosco** [comment]
Would the new `Subscribe` function satisfy this? https://pkg.go.dev/github.com/dosco/super-graph@v0.14.33/core?tab=doc#SuperGraph.Subscribe

**Comment by dosco** [comment]
Can we close this? Does the API linked in the previous comment satisfy SSE?

**Comment by frederikhors** [comment]
@dosco, will you please give me some more time to explore this topic?

Thank you.
