### ISSUE TITLE
Adding a lower level API

### ISSUE THREAD

**Issue by wttw** [dosco/graphjin#99]
**What would you like to be added**:

At the moment supergraph-the-library has a very narrow API, just enough to implement a graphql interface to an existing postgresql database and to act as the basis of supergraph-the-server. That's a great first step in allowing it to be embedded, and likely enough for 80% of use cases.

It's not particularly flexible, though. One approach to giving more control to the user would be providing hooks to insert code into different stages of the request processing. e.g. "isColumnVisible(schema, table, column) bool" as a generalization of the Blocklist configuration setting.

Another approach is to open up the internal workings as a public, lower-level API. That would both make it easy to insert code all through the request processing pipeline _and_ make it easy for people to add functionality we've not thought of yet, both for app-specific special cases and for experimenting with ideas that might be useful more widely.

**Why is this needed**:

As a trivial example, I'd like to provide graphql access to my applications database. The app is installed on customer's servers, and customers often add tables to the schema the app uses and additional columns to it's tables, and I don't want to leak that information. If I could call psql.NewDBSchema() to get a schema, sanitize it however I need to, then use that modified schema to create the rest of the handlers that would let me do that.

A more complex example - I'd like to support live search results. If I have access to the AST of the parsed graphql request that lets me cleanly see what where: clause was provided, and use that to filter change sets.

It's things that aren't universally useful enough to add to the core code, but which are too complex to add without visibility into the internal data structures.

There are several general questions before it's worth looking at specifics.

- Is this something enough people might find useful to be worth considering?
- Would it promote development of code / plugins that would be widely useful?
- Would opening up the internal data structures as part of a nominally public API make development and maintenance harder, for fear of breaking code using them?
- Are, e.g., the internal psql and qcode packages independent enough that they could usefully be pulled out as standalone packages.

**Comment by dosco** [comment]
Fair enough, I'm not against exposing more APIs but I tend to do them slowly and deliberately. This is because when an API or package is exported then you can't take it back without breaking backward compatibility, etc.  When I use an API internally then overtime I'm more confident about it's design at which point I expose it. This is the reason to keep `psql` and `qcode` packages internal for now.

Let's go with real work use-cases that you have and cannot currently handle with Super Graph that way it's not too open ended.

You should be able to handle the live search results example with subscriptions.

**Comment by dosco** [comment]
GraphJin is now a library with a rich API. You can include the entire service or just the GraphQL compiler in your app. https://pkg.go.dev/github.com/dosco/graphjin/core
